### ISSUE TITLE
Firebase Core

### ISSUE THREAD

**Issue by thirstyde** [firebase/flutterfire#10257]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (32448): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:203:7)
E/flutter (32448): <asynchronous suspension>
E/flutter (32448): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter (32448): <asynchronous suspension>
E/flutter (32448): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (32448): <asynchronous suspension>
E/flutter (32448): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
E/flutter (32448): <asynchronous suspension>
E/flutter (32448): #4      main (package:acoustic/main.dart:49:9)
E/flutter (32448): <asynchronous suspension>
```

How to solved this exeption
![image](https://user-images.githubusercontent.com/113355668/212080714-0b7b58ea-2cee-4198-9215-99dd9a6f4344.png)

**Comment by darshankawar** [comment]
@thirstyde 
The error probably indicates, that the engine / plugin isn't properly registered. Check below similar issues and see if they help in your case. It looks more like implementation issue rather than bug in plugin.

https://github.com/firebase/flutterfire/issues/9113
https://github.com/firebase/flutterfire/issues/9088

Also, since there's no relevant details provided in your description (code sample, flutter doctor), it's better to ask such questions on support channels like StackOverflow.
Closing from here.
