### ISSUE TITLE
[firebase_app_check] iOS: Add Support for the App Attest attestation provider

### ISSUE THREAD

**Issue by dsgriffin** [firebase/flutterfire#10278]
The `firebase_app_check` plugin does not currently support the `App Attest` attestation provider, and requires we use `DeviceCheck` (tested using latest versions of all relevant packages/devices). 

Please consider adding support for the newer/preferred `App Attest` method.

Related: #6940

https://github.com/firebase/flutterfire/blob/da36b9861b7d635382705b4893eed85fd672125c/packages/firebase_app_check/firebase_app_check/ios/Classes/FLTFirebaseAppCheckPlugin.m#L111-L125

**Comment by russellwheatley** [comment]
Hi @dsgriffin, at the moment, we do not have a way to support the AppAttestation provider. The problem is, you have to call `setAppCheckProviderFactory` before you configure your Firebase app. FlutterFire calls app configuration at [this point](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m#L47) when registering the `firebase_core` plugin. If you call `setAppCheckProviderFactory` after configuration, it does not change the provider (i.e. default is DeviceCheck provider). 

Quote from [documentation](https://firebase.google.com/docs/reference/ios/firebaseappcheck/api/reference/Classes/FIRAppCheck):

> /// NOTE: Make sure to call this method before `FirebaseApp.configure()`. If
/// this method is called after configuring Firebase, the changes will not take
/// effect.

We can take a look at whether there is anything that can be done about this, but at the moment, this is on hold. Sorry for the inconvenience.
