### ISSUE TITLE
[📚] Notifications not arriving in release mode after upgrade

### ISSUE THREAD

**Issue by MauScheff** [firebase/flutterfire#10318]
It's worth mentioning and highlighting that R8 may remove the handlers _firebaseMessagingForegroundHandler, _firebaseMessagingBackgroundHandler if these are not marked with @pragma('vm:entry-point').

It was a huge pain to figure this out... hope this helps.

**Comment by darshankawar** [comment]
@MauScheff 
This is already mentioned in the plugin example as below:

https://github.com/firebase/flutterfire/blob/fd3026a4c281fcd90b7fc9007ae39d226b19a66f/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L46

See if it answers your question.

**Comment by darshankawar** [comment]
I see, thanks for the feedback.

**Comment by russellwheatley** [comment]
Hey @MauScheff , this wasn't a `firebase_messaging` upgrade issue, it was an upgrade to flutter `3.3.0` as [evidenced here](https://github.com/firebase/flutterfire/issues/9446). 

@kevinthecheung What do you think about having a note in the [documentation here](https://firebase.google.com/docs/cloud-messaging/flutter/receive#apple_platforms_and_android)?

Example note:
<img width="832" alt="Screenshot 2023-01-27 at 08 49 44" src="https://user-images.githubusercontent.com/16018629/215045583-1fd7acfb-25e2-4715-b1c9-1fd80622ce9f.png">

Saying something like:
"Please be aware, if you're upgrading to Flutter >= `3.3.0`, you must add the `@pragma('vm:entry-point') ` annotation above your background message handling function for it to work in release mode. Otherwise, it may be removed during tree shaking."
