### ISSUE TITLE
🐛 [firebase_auth] com.google.android.gms:play-services-safetynet:17.0.0

### ISSUE THREAD

**Issue by ZXERSTON** [firebase/flutterfire#10387]
## Bug report

**Describe the bug**
Just submitted my app in PlayStore and received this:

com.google.android.gms:play-services-safetynet:17.0.0
This SDK version has a note from the SDK developer. Here's what the SDK developer told us:

The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline

I did a bit of research and saw someone mentioning that firebase auth is causing this. 

Anyone face the same issue?

**Comment by darshankawar** [comment]
@ZXERSTON 
This issue need to be handled and fixed by native firebase sdk itself, so flutterfire plugins can't do much about it.
There's similar issue open in android firebase sdk github in which you can follow-up for further updates: https://github.com/firebase/firebase-android-sdk/issues/3890

Closing from here.
