### ISSUE TITLE
🐛 [Flutter Fire UI] Bottom Overflowed by 3.7 pixels

### ISSUE THREAD

**Issue by Wild-in-Programming** [firebase/flutterfire#10385]
Greetings,

I am new to Firebase UI and am encountering an issue with the Sign In Page. It is displaying an error message of "BOTTOM OVERFLOWED BY 3.7 Pixels." I have researched previous similar issues such as #8396, #8941, and #9713 but have not been able to resolve the problem.
I have attempted to resolve the issue on both Chrome and Android platforms, however, the issue remains persistent. I am also using the Google Font package with the Pacifico text theme and I am wondering if this may be contributing to the issue.
I have attached a screenshot of the output screen for reference.

I would greatly appreciate any assistance in resolving this issue. Thank you.
![image](https://user-images.githubusercontent.com/68590772/216797612-b48ddbfb-3766-44c9-8740-1e8e02b933cf.png)

**Comment by darshankawar** [comment]
Thanks for the report @Wild-in-Programming 
Are you referring to `firebase_ui_auth` plugin ?



> using the Google Font package with the Pacifico text theme

If you don't use this package, do you still get the same error ?

If you are using the same plugin I referred above, the `readMe` of it, says to use the mentioned font as https://pub.dev/packages/firebase_ui_auth#profile-screen-icons

But since you are on `SignIn`, maybe this is different use case. How are you using the `google_fonts` package and where are you specifying the `Pacifico text theme` for `sign in` screen ?

**Comment by Wild-in-Programming** [comment]
Dear support team,

Thank you for responding to my query. 

> Are you referring to `firebase_ui_auth` plugin ?
I apologize for the confusion, but I'm not sure, my import statement is `import 'package:flutterfire_ui/auth.dart';`

I am pleasantly surprised to inform you that the previous issue has been resolved, however, I am encountering a new issue now. Whenever I try to sign in using Google, a message stating "An unknown error occurred" appears below the "Sign in with Google" button.

I appreciate your assistance and look forward to a resolution.

Thank you for your time.

**Comment by darshankawar** [comment]
> "An unknown error occurred" appears below the "Sign in with Google" button.

Please file a new issue by providing all relevant details as mentioned in the issue template.

Closing this issue based on above comment as resolved.
