### ISSUE TITLE
🐛 [cloud_firestore] Expected a value of type 'FieldPath', but got one of type 'LegacyJavaScriptObject'

### ISSUE THREAD

**Issue by rohansohonee1** [firebase/flutterfire#10451]
## Bug report

**Describe the bug**
After updating to cloud_firestore: 4.4.0, the update method is not working.

```
final Map<FieldPath, dynamic> data = {
        FieldPath.fromString('test'): 'test',
        FieldPath.fromString('value'): 1234,
      };
FirebaseFirestore.instance.collection('testCollection').update(data);
```

### Expected behavior
Should not give this error "Expected a value of type 'FieldPath', but got one of type 'LegacyJavaScriptObject'".

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.3 21G419 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
firebase_core: 2.5.0
cloud_firestore: 4.4.0
```

</details>

---

**Comment by rohansohonee1** [comment]
Please do test this on all the platforms also, not just the test cases.

**Comment by onayem** [comment]
I face the same issue, too. It started happening after I switched to `cloud_firestore: 4.4.0`. (I also upgraded all other firebase packages I use). 
All methods stays the same, nothing is changed. 
`add()` , `get()` , `set()` all working, the only problem is with the `update()`.
I am developing for the web platform.

### Flutter doctor:
```[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.2486], locale en-AT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.1)
[√] Connected device (3 available)
[√] HTTP Host Availability```

**Comment by spideythewebhead** [comment]
I can verify the error too

It seems it related to this [PR](https://github.com/firebase/flutterfire/pull/10388) 

More specifically https://github.com/firebase/flutterfire/pull/10388/files#diff-4f492214e4a65ffeb40aac41adc7570e0c07db1d3acc74d3e3a68c923b07a1b0R24 this function should have the following signature (firestore_interop.FieldPath instead of FieldPath)

```dart
  static Map<firestore_interop.FieldPath, dynamic>? encodeMapDataFieldPath(
      Map<Object, dynamic>? data) {
    if (data == null) {
      return null;
    }
    Map<firestore_interop.FieldPath, dynamic> output =
        <firestore_interop.FieldPath, dynamic>{};
    data.forEach((key, value) {
      output[valueEncode(key)] = valueEncode(value);
    });
    return output;
  }
```

But there is a second problem too after modifying the code to this. 
https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart#L370

the `updateDoc` call does not support `[firestore_interop.FieldPath` values inside a json object.

Valid usage: `updateDoc(docRef, fieldPath, data)`
Invalid usage:

```dart
updateDoc(docRef, {fieldPath: value`})
```

I would suggest to allow `FieldPath` type in dart side but to transform this value into a string separated by dots for the web part

**Comment by saklani** [comment]
I can verify this error as well. I was unable to build the project after downgrading back to `4.3.2` turns out the problem is in `cloud_firestore_platform_interface: 5.11.0`. 
Editing pubspec.lock manually and fetching `cloud_firestore_platform_interface: 5.10.2`, works for now.

**Comment by onayem** [comment]
Is there a chance we get a hotfix for this bug? I can not manage to keep on working on the project. 
`update()` is needed at many points. 
No solution worked for me:
- Since the method still expects `Map<Object, Object?> data`, I cannot place `FieldPath` directly as a parameter. 
- Turning map object keys into `FieldPath` does not work either, it gives the same error.
- Even if I downgraded `cloud_firestore` back to `4.3.2` and manually changed the version of  `cloud_firestore_platform_interface` to `5.10.2`, I could not make it run. It reverts back to `5.11.0` when I try to build or run the project.

Help needed.

**Comment by deepak-agendaboa** [comment]
For now, we are using the older version of cloud_firestore by overriding it in dependency_overrides:

```
dependency_overrides:
  cloud_firestore: 4.3.2
  cloud_firestore_platform_interface: 5.10.2
  cloud_firestore_web: 3.2.2
```

**Comment by bksbora** [comment]
I guess your model is partly absent or extra , can you try .set instead of .update method ?

**Comment by darshankawar** [comment]
Thanks for the report and findings. Seeing the same error upon running using plugin example with latest version.

https://github.com/firebase/flutterfire/issues/10451#issuecomment-1430522535

Related error: 
```
cloud_firestore-4.4.0/lib/src/document_reference.dart:177:76: Error: The argument type 'Map<FieldPath, dynamic>' can't be
assigned to the parameter type 'Map<String, dynamic>'.
```

**Comment by Lyokone** [comment]
Thanks for the report, I'm investigating

**Comment by Lyokone** [comment]
This PR is fixing the bug; I'm investigating why it was not caught by e2e tests.

**Comment by rakib205** [comment]
Any fix?

**Comment by DouglasCarterBor** [comment]
@deepak-agendaboa, thank you for your help!

For now we have the downgrade left.

`dependency_overrides:
  cloud_firestore: 4.3.2
  cloud_firestore_platform_interface: 5.10.2
  cloud_firestore_web: 3.2.2`

**Comment by fadlialakbar** [comment]
any fix?

**Comment by Lyokone** [comment]
Fix will be released today

**Comment by edimarvirtual** [comment]
Hello, I also have the same problem, (I tested web and native macOS, **the problem only occurs on the web platform)**.

I tried to update now via command
`flutter pub upgrade firebase_core firebase_auth firebase_storage cloud_firestore`

I saw that it will be fixed today, but there is still no fix available, I'm following this issue, as soon as someone manages to update, share it here, please

Thanks

**Comment by Lyokone** [comment]
It was released as part of the latest [cloud_firestore_web](https://pub.dev/packages/cloud_firestore_web) version. Updating to cloud_firestore 4.4.1 will contain the update.

**Comment by bgetsug** [comment]
Was this tested with values of `FieldValue.arrayUnion(...)`? Now instead of the error in the title of this issue, I'm seeing `Function updateDoc() called with invalid data. Unsupported field value: a custom _FieldValueArrayUnion object `. I'll open a new ticket 😞

**Comment by onayem** [comment]
I can verify the comment above. I face the same issue when `FieldValue.delete()` is used.

Here is the function:
```
... .collection.doc("myDoc").update({'myField.myNestedField': FieldValue.delete()});
```

Here is the error:
```
Function updateDoc() called with invalid data. Unsupported field value: a custom _FieldValueDelete object 
(found in field 'myField.myNestedField' in document myDoc)
```

Shall we open a new issue or reopen this one and continue here?

**Comment by edimarvirtual** [comment]
Thank you @Lyokone  😊👍, After Updating to version **4.4.1** it resolved here, in some places it is still triggering the following error (**only for the web platform**):
  **_"Function updateDoc() called with invalid data. Unsupported field value: a custom LinkedMap object (found in field Status in document Filiais/1)"_**

I've seen an old thread regarding a similar error on:
[https://stackoverflow.com/questions/48156234/function-documentreference-set-called-with-invalid-data-unsupported-field-val](https://stackoverflow.com/questions/48156234/function-documentreference-set-called-with-invalid-data-unsupported-field-val)

I'm seeing if this resolves the other errors, **_although I find it odd that it works on native macOS and doesn't work on the web_**

I'm still going to keep an eye on this topic because it may have updates that solve the other problems

Thanks
