### ISSUE TITLE
🐛 [Firebase Auth] Play Console blocking the app rollout on using com.google.android.gms:play-services-safetynet:17.0.0

### ISSUE THREAD

**Issue by AndrewTran2018** [firebase/flutterfire#10823]
Play Console blocking the app rollout:
__________________________________________________________
com.google.android.gms:play-services-safetynet:17.0.0
This SDK version has a note from the SDK developer. Here's what the SDK developer told us:

The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline
________________________________
firebase_auth 4.4.2
 cloud_firestore: ^4.4.4

**Comment by danagbemava-nc** [comment]
Hi @AndrewTran2018,
This issue needs to be handled and fixed by native firebase sdk itself, so the flutterfire plugins can't do much about it.
There's a similar issue open in the android firebase sdk github in which you can follow up on for further updates: https://github.com/firebase/firebase-android-sdk/issues/3890

Closing from here.
