### ISSUE TITLE
`pushOnBackgroundMessage` platform method not implemented.

### ISSUE THREAD

**Issue by gowthaman13** [firebase/flutterfire#10835]
The error message "pushOnBackgroundMessage platform method not implemented" typically occurs when your Flutter app receives a push notification while it is in the background and the onBackgroundMessage method has not been implemented.

**Comment by darshankawar** [comment]
@gowthaman13 
There's not much details you provided except the error message which is not helpful to properly address the issue. Please use [issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we can help you properly.
Closing for now due to lack of details.
