### ISSUE TITLE
Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.

### ISSUE THREAD

**Issue by Pradeepa651** [firebase/flutterfire#10900]
W/DynamiteModule( 3889): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 3889): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 3889): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
W/ProviderInstaller( 3889): Failed to report request stats: reportRequestStats [class android.content.Context, long, long]

**Comment by danagbemava-nc** [comment]
Hi @Pradeepa651,
When opening an issue, please use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.
Currently, no details are provided so we can't proceed to make it actionable.
Closing for now due to lack of details.
