### ISSUE TITLE
🐛 [firebase auth] FirebaseAuthException ([firebase_auth/invalid-credential] Invalid access_token, error code 43)

### ISSUE THREAD

**Issue by harryandroiddev** [firebase/flutterfire#10935]
FirebaseAuthException ([firebase_auth/invalid-credential] Invalid access_token, error code 43)

**Comment by darshankawar** [comment]
@harryandroiddev 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
Just posting the single line error isn't helpful. I'll close it for now as there's not enough details to properly address the issue. You may file new issue using template.
