### ISSUE TITLE
 No top-level getter '_firebaseMessagingBackgroundHandler' declared

### ISSUE THREAD

**Issue by paramesh0** [firebase/flutterfire#10976]
## Bug report

**Describe the bug**
The app's backdrop isn't functioning. Not working is Firebase messaging. I start the calling function, but it doesn't do anything.

### Steps to reproduce

1. the. application fully closed.  to trigger firebase message.
2.Error
`E/flutter (26139): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception: E/flutter (26139): NoSuchMethodError: No top-level getter '_firebaseMessagingBackgroundHandler' declared. E/flutter (26139): Receiver: top-level E/flutter (26139): Tried calling: _firebaseMessagingBackgroundHandler`

### Expected behavior

to open firebase listen to trigger calling function.
The andriod version 13

### Flutter dependencies:
  firebase_core: ^2.9.0
  firebase_crashlytics: ^2.7.2
  firebase_messaging: ^14.0.0

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @paramesh0, is your `_firebaseMessagingBackgroundHandler` annotated with `@pragma(vm:entry-point)` as shown in example code here https://github.com/firebase/flutterfire/blob/bb9c5523964d9e11a82f80ceb74d808808cc2a4c/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#LL46C1-L46C2

If it is, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you
