### ISSUE TITLE
receive twice notification when app is background 

### ISSUE THREAD

**Issue by iresolveservices** [firebase/flutterfire#11021]
receive twice notification when app is background

**Comment by smolugu** [comment]
Leave the background handler empty

**Comment by iresolveservices** [comment]
so how we handle local notifications

**Comment by iresolveservices** [comment]
and notification redirections when app is in background

**Comment by iresolveservices** [comment]
so is there any proper way handle background and foreground notification along with their actual

**Comment by harryandroiddev** [comment]
This issue is in andorid or ios ?

**Comment by darshankawar** [comment]
@iresolveservices 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with. 
For now, please provide `flutter doctor -v`, platform along with minimal code sample that shows the reported behavior.
See this similar issue that was fixed last year for reference and see if it helps in your case or not: https://github.com/firebase/flutterfire/issues/9912
