### ISSUE TITLE
🐛 [dynamic_links,ios] generated link always opens google play on ios device 

### ISSUE THREAD

**Issue by devmohamedslama** [firebase/flutterfire#11128]
## Bug report

**dynamic links not opening app store**

**Comment by darshankawar** [comment]
@devmohamedslama 
When you open an issue, please try to use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&projects=&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.
I'll close it for now  due to lack of details. You can take a look at [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links/example) and see if using it, you get same behavior or not or there's any missing config / implementation at your end.
