### ISSUE TITLE
🐛 FirebaseMessaging FirebaseMessaging.onMessage.listen((){}) doesn't work in IOS

### ISSUE THREAD

**Issue by MrunalrajRedij** [firebase/flutterfire#11137]
**Describe the Issue**
`FirebaseMessaging.onMessage` doesn't get called in IOS. The device is showing the notification but I am not seeing logs inside this callback printed anywhere.

### Expected behavior:
I want to run some methods whenever I receive an FCM notification in the foreground. For that, I want a callback whenever I get an FCM notification, where I can execute methods and logs.

**Comment by darshankawar** [comment]
@MrunalrajRedij 
When opening an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with. Just mentioning that a method doesn't work, isn't helpful to analyze properly.

Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation and `flutter doctor -v` so that we can take a look.

Also, you can also take a look at [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if using it you get same behavior or not.
