### ISSUE TITLE
🐛  FLTFirebaseAuth: An error occurred while calling method Auth#signInWithCredential, errorOrNil => (null)

### ISSUE THREAD

**Issue by nadeemabualarayes** [firebase/flutterfire#11189]
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithCredential, errorOrNil => (null)

**Comment by darshankawar** [comment]
@nadeemabualarayes 
Looking at the error, it seems to be similar to https://github.com/firebase/flutterfire/issues/10865, so please follow-up in it for further updates. I'll close this as a duplicate. If you disagree or your use case is different than the linked issue, write in comments and I'll reopen it.

Also, please note that, when opening an issue, try to use new issue template and fill out requested details so that we'll have enough info to work with.
