### ISSUE TITLE
🐛 [crashlytics] _HttpClient.openUrl, No host specified in URI. Error thrown resolving an image codec.

### ISSUE THREAD

**Issue by MominRaza** [firebase/flutterfire#11185]
## Bug report

**Describe the bug**
This carsh is reported in Crashlytics dashboard as Repetitive crashes

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Invalid argument(s): No host specified in URI. Error thrown resolving an image codec.
       at _HttpClient.openUrl(dart:_http)
       at IOClient.send(io_client.dart:63)
       at HttpFileService.get(file_service.dart:35)
       at WebHelper._download(web_helper.dart:121)
       at WebHelper._updateFile(web_helper.dart:103)
       at WebHelper._downloadOrAddToQueue(web_helper.dart:71)
```

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@MominRaza 
Looking at the error log, there are no entries of `firebase_crashlytics` plugin and the error you are reporting may not be related to flutterfire. I suggest you to ask this question on support channels like StackOverflow by trying to provide minimal code sample so that it'll be helpful to give a solution.
Closing for now. If you disagree, write in. comments and I'll reopen it.
