### ISSUE TITLE
🐛 [firebase_ui_firestore] Invalid index throw when unsubscribing on Flutter web

### ISSUE THREAD

**Issue by wer-mathurin** [firebase/flutterfire#11235]
## Bug report

**Describe the bug**
I'm not able to reproduce on a constant basis, but I know what cause it.  Just catch this error when debugging and catch all errors:

`ChromeProxyService: Failed to evaluate expression 'firestore_interop': InternalError: Expression evaluation in async frames is not supported. No frame with index 16..`

It does not make the app failing, but this is annoying

Basically in the query_builder.dart in the _listenQuery

The error is thrown when the `_querySubscription?.cancel()` have not the chance to complete before resubscribing again => `querySubscription = query.snapshots().listen(...` is called before cancel completion

Can be resolve by making the method async and awaiting
`void _listenQuery({bool nextPage = false}) async {
    await _querySubscription?.cancel();
...
`

### Steps to reproduce
Not able to have it each time !!!

**Comment by darshankawar** [comment]
Thanks for the report. I tried with the plugin example on web, but didn't get the reported error.
Although I have seen similar error reports not specific to flutterfire, but in flutter repo as well. One such is https://github.com/flutter/flutter/issues/121798

Since the error says `InternalError: Expression evaluation in async frames is not supported.`, maybe it has to do with how async in web works or not correctly, but we'll need a concrete steps to replicate in order to properly address the issue.
