### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS

### ISSUE THREAD

**Issue by iresolveservices** [firebase/flutterfire#11244]
![WhatsApp Image 2023-07-10 at 11 45 54 AM](https://github.com/firebase/flutterfire/assets/42065876/a8f1990c-2162-4900-9ee7-5d21a8a11f2b)

```
E/FirebaseInstanceId( 9566): Topic sync or token retrieval failed on hard failure exceptions: TOO_MANY_REGISTRATIONS. Won't retry the operation.
E/flutter ( 9566): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS
E/flutter ( 9566): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 9566): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566): #3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
E/flutter ( 9566): <asynchronous suspension>
E/flutter ( 9566): 
```

**Comment by darshankawar** [comment]
@iresolveservices 

`[firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS"` probably indicates your device is already registered or being reused many times and may not be specific to firebase_messaging, but could be related to native  Android.

Check below links and see if they help in your case or not:

https://stackoverflow.com/a/48439819
https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase

https://stackoverflow.com/questions/5641511/too-many-registrations-error-code-in-android-c2dm
https://www.youtube.com/watch?v=A-lF3IlUgKI

Closing for now, as this doesn't seem to be occuring due to the plugin as it is a thin wrapper around native Firebase sdks. If you get a concrete steps to replicate along with minimal code sample that consistently triggers this error, write in comments with details and I'll reopen it.

**Comment by iresolveservices** [comment]
Real time devices factory reset not possible. and our two and more client facing same issue and they install app only once.

**Comment by iresolveservices** [comment]
> @iresolveservices
> 
> `[firebase_messaging/unknown] java.io.IOException: TOO_MANY_REGISTRATIONS"` probably indicates your device is already registered or being reused many times and may not be specific to firebase_messaging, but could be related to native Android.
> 
> Check below links and see if they help in your case or not:
> 
> https://stackoverflow.com/a/48439819 https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase
> 
> https://stackoverflow.com/questions/5641511/too-many-registrations-error-code-in-android-c2dm https://www.youtube.com/watch?v=A-lF3IlUgKI
> 
> Closing for now, as this doesn't seem to be occuring due to the plugin as it is a thin wrapper around native Firebase sdks. If you get a concrete steps to replicate along with minimal code sample that consistently triggers this error, write in comments with details and I'll reopen it.

that not use full
