### ISSUE TITLE
notification not show in android 12

### ISSUE THREAD

**Issue by rezadevelopers2** [firebase/flutterfire#11356]
Hello, the program works properly until Android 11, but notifications are not received from Android 11 and above

`[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)`

**Comment by darshankawar** [comment]
@rezadevelopers2 
The `post_notification` feature was added for Android to support Android 13 OS. See this PR : https://github.com/firebase/flutterfire/pull/9348 and in order to use that feature, the sdk versions need to be updated as mentioned in the PR along with `android:exported="true"` in manifest. 

Check the same and see if it helps to resolve the issue you are facing.
