### ISSUE TITLE
🐛 [Firebase Analytics] There is a major problem in analytics

### ISSUE THREAD

**Issue by dishankjindal1** [firebase/flutterfire#11384]
## Bug report

Bug report
Describe the bug
I am able to use two different firebase google-services.json from different firebase project scope which has the same package name to log analytics in the analytics dashboard.

**Comment by darshankawar** [comment]
@dishankjindal1 
What exactly is the problem / issue you are reporting here ? Is it using 2 different json files with same package name ?
If you are using flavors, then the setup you are describing is expected I think because Changing the google-services.json file depending on the build flavor is indeed a common way to select between projects at build time.

If this isn't your case, then provide more details, exact issue / error you are seeing.

**Comment by dishankjindal1** [comment]
Hey @darshankawar - the problem was user is able to receive notification even when google-services.json is created from 2 completely different accounts but sharing the same app identifier.

So in this case, I was able to trigger firebase push notification to a company app using my personal firebase account because i purposely create duplicate app identifier
