### ISSUE TITLE
🐛 [firebase-messaging] MessageOpenedApp or onDidReceiveNotificationResponse not trigger

### ISSUE THREAD

**Issue by ItayBarFaye** [firebase/flutterfire#11475]
## Bug report

**Describe the bug**
User getting silent push notification (only data in payload) while app is in foreground, when tapping the notification nothing happened I try to navigate to different screen but the nothing trggered.

### Expected behavior

Navigate to screen by type.

**Comment by darshankawar** [comment]
@ItayBarFaye 
Can you try running the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) by removing the android service file in `android/app/google-services.json` and run `flutterfire configure` with your own project configuration and run your scenario to check if it works or not ?

**Comment by ItayBarFaye** [comment]
Sorry but I didn't specified it's only happen on IOS

**Comment by darshankawar** [comment]
You may try the same by running the [script](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/scripts) that sends message from nodejs admin SDK directly and check on iOS.
If that doesn't properly represent your case, please provide us minimal reproducible code sample, flutter doctor -v, plugin version and how are you sending the data message payload including a sample that we can use so that we can properly address the issue.

**Comment by ItayBarFaye** [comment]
I'm also using nodejs admin SDK, if I'll send  it this way with the notification it will work but if I'm sending only data it won't work.

**Comment by ItayBarFaye** [comment]
I managed to overcome this issue by using function from AppDelegate 

override func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
self.nativeChannel?.invokeMethod("notificationSelected", arguments: userInfo)
completionHandler()
}

It worked for me.

**Comment by darshankawar** [comment]
Good to know the issue is resolved. For more reference about it, you may go through https://github.com/firebase/flutterfire/issues/10082 and underlying comments and see if it helps further in your case.
