### ISSUE TITLE
Deeplink ios after deploying the website doesn't work

### ISSUE THREAD

**Issue by RanoshTarek** [firebase/flutterfire#11490]
1. I hosted the website in the default domain 
2. then I created another domain 
3. I use the other domain to handle my deep link which works fine on Android but ios, not 
4. ios open the preview screen then redirect to the hosted website (default domain) expected to open ios app like android 
5. firebase.json
`{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "headers": [
      {
        "source": "/.well-known/apple-app-site-association",
        "headers": [
          {
            "key": "Content-Type",
            "value": "application/json"
          }
        ]
      },
      {
        "source": "apple-app-site-association",
        "headers": [
          {
            "key": "Content-Type",
            "value": "application/json"
          }
        ]
      }
    ],
    "appAssociation": "NONE",
    "rewrites": [
      {
        "source": "**",
        "dynamicLinks": true
      },
      {
        "source": "/**",
        "dynamicLinks": true
      },
      {
        "source": "/links/**",
        "dynamicLinks": true
      },
      {
        "source": "/sina-app.com/**",
        "dynamicLinks": true
      },
      {
        "source": "https://sina-app.com/**",
        "dynamicLinks": true
      },
      {
        "source": "sina-app.com/**",
        "dynamicLinks": true
      },
      {
        "source": "sina-app.com/*",
        "dynamicLinks": true
      }
    ]
  }
}`

_Originally posted by @RanoshTarek in https://github.com/firebase/flutterfire/discussions/11489_

**Comment by darshankawar** [comment]
@RanoshTarek 
When opening an issue, please try to use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&projects=&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.
Based on the info you provided, it is not clear if it is related to flutterfire's `firebase_dynamic_link` plugin or not, or only using flutter and without any code sample, we won't be able to help us properly.

Closing for now due to lack of details.
