### ISSUE TITLE
🐛 [firebase_auth] BLOCKING_FUNCTION_ERROR_RESPONSE: Cloud function deadline exceeded.

### ISSUE THREAD

**Issue by Buckwich** [firebase/flutterfire#11637]
## Bug report

**Describe the bug**
We are using Firebase Auth with Identity Platform. Sometimes (around 1 out of 50) the create user functions returns an error: `BLOCKING_FUNCTION_ERROR_RESPONSE:Cloud function deadline exceeded.`. The action used is `signUpPassword` and the blocking function `Before account creation (beforeCreate)` is set to `None`. The actual account creation still happens in the background, so further retries error with `The email address is already in use by another account`. 

### Steps to reproduce

1. Repeatetly try `FirebaseAuth.createUserWithEmailAndPassword` (not to fast as this could lead to other quota errors)
2. Hopefully get the error as described above

### Expected behavior

As `signUpPassword` should be a create event, no blocking function should be called (as we have configured none) and the error should not be possible.

**Comment by darshankawar** [comment]
@Buckwich 
I suggest you to reach out to [Firebase support](https://firebase.google.com/support), as it doesn't seem to be a plugin issue, but could be coming from firebase server itself. flutterfire plugins are thin wrappers around native Firebase sdks, so it is unlikely that the error could be causing due to plugin code.
