### ISSUE TITLE
🐛 [Flutter Auth Phone] Phone auth in ios simulation works but not on real device

### ISSUE THREAD

**Issue by arnair** [firebase/flutterfire#11706]
## Bug report

I add phone auth on my flutter app and when i do it on the ios simulator it works fine but when i install it in a real ios device after putting my phone number nothing happen. (in a android real device works)

### Steps to reproduce

1. Add Phone Auth and check that it works in the simulator
2. Upload ipa to test flight
3. Execute the testflight app on a real device

### Expected behavior

I would be able to login with the phone number in the real device,

## Additional context

I have activated the background and normal notification with the profile.

</details>

---

### Flutter dependencies

  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  cloud_functions: ^4.4.2
  firebase_storage: ^11.2.8
  firebase_analytics: ^10.5.1  
  firebase_messaging: ^14.6.9

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@arnair 
This doesn't seem to be a bug in plugin, but looks like a config / setup issue at your end. If it works on simulator, then it isn't a bug because the code doesn't differ between devices. Check the [documentation](https://firebase.google.com/docs/auth/flutter/phone-auth#setup) for iOS once again and see if you are missing any setup / config that might be leading to the behavior you are seeing.
Closing from here. If you have further issues, you may raise this in discussion forum or on StackOverflow.
