### ISSUE TITLE
🐛. problem occurred configuring project ':firebase_auth'.

### ISSUE THREAD

**Issue by Pradeepa651** [firebase/flutterfire#11748]
## Bug report

**Describe the bug**
A clear and concise description of what the bug is. problem occurred configuring project ':firebase_auth'.
> Could not load compiled classes for build file 'C:\Users\PRADEEPA G\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_auth-4.11.1\android\build.gradle' from cache.

**Comment by darshankawar** [comment]
@Pradeepa651 
Can you try by clearing the gradlew cache and run again ?
Also, When you open an issue, please try to use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&projects=&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with. Just providing snippet of the error log won't help us much to properly address the issue.
Closing for now due to lack of details.
