### ISSUE TITLE
🐛 [Firestore] Windows build error

### ISSUE THREAD

**Issue by HeroRickyGAMES** [firebase/flutterfire#11814]
I found out that Firebase now has official support for Windows and decided to port my app to Windows.
When I finished testing and went to make a production version, the log gave me several errors and the build did not complete

LOG:
[log.txt](https://github.com/firebase/flutterfire/files/13229451/log.txt)

**Comment by hwkim1127** [comment]
AFAIK, it's only for development only. Production on Windows is not supported since Firebase does not actually support Desktop.

there is a discussion here
https://github.com/firebase/flutterfire/discussions/5557


you can probably file issues here
https://github.com/firebase/firebase-cpp-sdk/issues

here
https://firebase.google.com/support/troubleshooter/report/features

and here
https://firebase.uservoice.com/forums/948424-general/suggestions/46591750-desktop-windows-linux-macos-support-for-flutte

**Comment by HeroRickyGAMES** [comment]
Ok, congratulations on the initiative! May it soon be in production for everyone to use! Thanks

**Comment by EstebanAlvarado433** [comment]
Understood, if you can use firebase but only in debug mode, I hope one day it arrives for production, meanwhile internally we will use debug mode for the application

**Comment by darshankawar** [comment]
@HeroRickyGAMES and everyone else facing the issue, the windows support for the plugin has just been added recently: https://github.com/firebase/flutterfire/pull/11516 so it is unlikely that it'll run properly in release / production mode.
You may also keep an eye on https://github.com/FirebaseExtended/flutterfire_desktop/issues/52 for further updates.

Based on https://github.com/firebase/flutterfire/issues/11814#issuecomment-1789683442, I'll close it as such. If anybody disagrees, write in comments and I'll reopen it.
