### ISSUE TITLE
🐛[firebase_auth] Wrong error message is returned for unregistered email 

### ISSUE THREAD

**Issue by mrmhthegreat** [firebase/flutterfire#11826]
`  try {
      await auth.signInWithEmailAndPassword(
          email: email.text, password: pass.text);
    } on FirebaseAuthException catch (e) {
      if (e.code == 'user-not-found') {} else if (e.code == 'wrong-password') {
        toast("Wrong password provided for that user.");
      } else {
        toast(e.toString());
      }`
**when try to used the email which is not register yet it still give error Invalid credentials instead it should give error code user-not-found and also when i use email tha is register with wrong password i give  Invalid credentials  error code instead it should give wrong-password**

**Comment by mrmhthegreat** [comment]
### firebase_auth: 4.12.1

**Comment by danagbemava-nc** [comment]
Hi @mrmhthegreat, your project probably has email enumeration protection enabled. You should disable it if you want to see the message you're looking for. See https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection.

Bear in mind that this is not recommended. 

I'll be closing this since this is a broader change to the identity platform and not something peculiar to the plugin. 

Thank you
