### ISSUE TITLE
🐛 [firestore] Not able to filter/query on fields that are null

### ISSUE THREAD

**Issue by puf** [firebase/flutterfire#11874]
## Bug report

I have a query that tries to retrieve documents with a (date) field that has a null value. 

    const query = FirebaseFirestore.instance.collection("77468864").where("date", isEqualTo: null);
    var snapshot = await query.get();
    print('Got snapshot with ${snapshot.size} documents');

The Flutter code (when run on web, I didn't test other platforms) incorrectly returns documents with an actual date value, while the corresponding JavaScript code does not return these documents.

### Steps to reproduce

0. I have a collection with one document that has two fields (`date` and `string`), both of which have a value.
1. Go to https://zapp.run/edit/firestore-query-null-date-zr1q06yyr1r0
2. Check the log output to see that the code returns a document with a non-null `date` field
3. Go to https://stackblitz.com/edit/firestore-v9-query-null-date?file=index.js
4. Check the log output to see that the code returns no documents

### Expected behavior

I expect the Flutter and JavaScript projects to show the same result, given that they run an equivalent query on the same data.

---

## Additional context

Originally reported here: https://stackoverflow.com/q/77468864

**Comment by Ehesp** [comment]
I believe there's a specific isNull named argument for this. I believe the reason was that there's no concept of undefined in Dart, so it had to be specific when you want to filter by null

**Comment by puf** [comment]
Thanks Elliot! 
I should've known this, especially since I'm pretty sure I used the `isNull` overload in the past. 

Undefined and `null` are different concepts though. Why can't the Flutter wrapper recognize the `null` value that I used in my testbed: `.where("date", isEqualTo: null)`?

**Comment by danagbemava-nc** [comment]
Hi @puf, should this be treated as a feature request?

**Comment by russellwheatley** [comment]
Hey @puf, you have to use `isNull` named argument in the query because we check the value in queries here:https://github.com/firebase/flutterfire/blob/e51d2a2d287f4162f5a67d8200f1bf57fc2afe14/packages/cloud_firestore/cloud_firestore/lib/src/query.dart#L658-L659

If the value is `null`, it does not become part of the query (as you can see in the link above). There really is no way around this as the API is currently implemented. We can't check whether the named arg was intentionally set as `null` by the user or unintentionally set (i.e. it is a nullable named argument).

Firestore doesn't allow `undefined` values set in the documents,  the concept of `undefined` is a quirk of JavaScript and is not cross platform compatible as far as I'm aware.

**Comment by puf** [comment]
Thanks for clarifying Russel. Do any of our SDKs for other languages drop `null` values like that? Or is there something idiomatic Flutter about dropping `null` value?

**Comment by russellwheatley** [comment]
It is more an issue with the way the API was initially designed. In an ideal world, the operator and the value would be separate arguments. This would allow `null` values  to be used on queries for `isEqualTo` & `isNotEqualTo`. But, because the operator and the value are set as one named argument, we cannot ascertain whether a `null` value was set by the user or not for that particular named argument (i.e. `isEqualTo` & `isNotEqualTo`).

**Comment by russellwheatley** [comment]
Hmmm, I've done a little bit of digging into this and there might be a way around it. I'll see what we can do 🤔

**Comment by Ehesp** [comment]
Could we make the default values of each argument a const/symbol which is internal, and if it's that value, skip it?

**Comment by russellwheatley** [comment]
@Ehesp  We have a PR: https://github.com/firebase/flutterfire/pull/11896

We use a sentinel to check if the value was set by the user: https://github.com/firebase/flutterfire/pull/11896/files#diff-c388154c29616d9c4eff4b583681b56e75ae1f0291f6c31db037d3d1e85fdd65R9
