### ISSUE TITLE
This issue has been improved after Flutter 3.7, and it can now be called on any isolated platform channel. Can Firebase message solve this problem now?

### ISSUE THREAD

**Issue by fe-spider** [firebase/flutterfire#12033]
Hi @moda20 
Thanks for the example. It was a bit broken but digging through the code it's clear that this is just a duplicate of https://github.com/flutter/flutter/issues/13937
Not being able to call platform channel methods from a secondary isolate is just a limitation of flutter for now. You can try to get around this using a package like `isolate_handler` but given that the background message handler is already in a secondary isolate it will probably still take some tinkering to get to work.
Since this is a limitation on the flutter side there isn't much we can do here.
Thank you

_Originally posted by @markusaksli-nc in https://github.com/firebase/flutterfire/issues/4958#issuecomment-777348634_

**Comment by darshankawar** [comment]
@fe-spider 
Please don't use comments from other issues to file a new issue. The link you shared is two years old.
In order to properly address the issue you are reporting, please try to use new issue template, fill out requested details so that we'll have enough info to work with.
Closing for now, due to lack of details.
