### ISSUE TITLE
🐛 [cloud_firestore] Gradle 8 incorrect package error

### ISSUE THREAD

**Issue by g-apparence** [firebase/flutterfire#12117]
## Bug report

**Describe the bug**
- upgrading the latest version of firebase auth forced me to also upgrade to Gradle 8. 
But now it requires to use namespace inside the build.gradle and not in manifest. 
So all firebase flutter plugin has to change this simultaneously. 

### Steps to reproduce

1. Upgrade firebase flutter auth plugin to latest version
2. run your app with firestore plugin on android
3. See error or incorrect behavior
```bash
Execution failed for task ':cloud_firestore:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="io.flutter.plugins.firebase.firestore" found in source AndroidManifest.xml: /Users/mcfly/.pub-cache/hosted/pub.dev/cloud_firestore-4.14.0/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="io.flutter.plugins.firebase.firestore" from the source AndroidManifest.xml: /Users/mcfly/.pub-cache/hosted/pub.dev/cloud_firestore-4.14.0/android/src/main/AndroidManifest.xml.
```

### Expected behavior

App builds and launch

**Comment by darshankawar** [comment]
Thanks for the report @g-apparence 
I tried by upgrading `firebase_auth` and `cloud_firestore` versions to the latest and ran the firestore plugin example on Android which compiled properly.
In the plugin example, I see that all plugins now support AGP 8.0 and has below addition:

<img width="741" alt="Screenshot 2024-01-08 at 5 56 49 PM" src="https://github.com/firebase/flutterfire/assets/67046386/c9808068-aa9f-4ba7-8981-e25dc6481da1">

Also see https://github.com/firebase/flutterfire/pull/11699

**Comment by g-apparence** [comment]
I'm still having this 

```
6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':cloud_firestore:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="io.flutter.plugins.firebase.firestore" found in source AndroidManifest.xml: /Users/mcfly/.pub-cache/hosted/pub.dev/cloud_firestore-4.14.0/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="io.flutter.plugins.firebase.firestore" from the source AndroidManifest.xml: /Users/mcfly/.pub-cache/hosted/pub.dev/cloud_firestore-4.14.0/android/src/main/AndroidManifest.xml.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

With 
```
cloud_firestore: ^4.14.0
```

and gradle 
```
classpath 'com.android.tools.build:gradle:8.1.1'
```

**Comment by darshankawar** [comment]
Thanks for the update. I tried using the plugin example but didn't get the reported error, but based on the report and `namespace` error, I'll keep the issue open for team's input and tracking.

**Comment by g-apparence** [comment]
Yes don't hesitate to ask more infos if you need. 
It happened since a month.

**Comment by Oppong** [comment]
Hi, i am also facing this issue after updating my firestore package

`
 Execution failed for task ':cloud_firestore:processDebugManifest'.
[        ] > A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
[        ]    > Incorrect package="io.flutter.plugins.firebase.firestore" found in source AndroidManifest.xml:
C:\Users\ampon\AppData\Local\Pub\Cache\hosted\pub.dev\cloud_firestore-4.14.0\android\src\main\AndroidManifest.xml.
[        ]      Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
[        ]      Recommendation: remove package="io.flutter.plugins.firebase.firestore" from the source AndroidManifest.xml:
C:\Users\ampon\AppData\Local\Pub\Cache\hosted\pub.dev\cloud_firestore-4.14.0\android\src\main\AndroidManifest.xml.



Caused by: java.lang.RuntimeException: Incorrect package="io.flutter.plugins.firebase.firestore" found in source AndroidManifest.xml:
C:\Users\ampon\AppData\Local\Pub\Cache\hosted\pub.dev\cloud_firestore-4.14.0\android\src\main\AndroidManifest.xml.
[        ] Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
[        ] Recommendation: remove package="io.flutter.plugins.firebase.firestore" from the source AndroidManifest.xml:
C:\Users\ampon\AppData\Local\Pub\Cache\hosted\pub.dev\cloud_firestore-4.14.0\android\src\main\AndroidManifest.xml.

`
Waiting for it to fixed so that i can successfully run my app

**Comment by Lyokone** [comment]
Hello @g-apparence, could you provide a repo that can be easily cloned to see in which configuration this happens? Our gradle config should allow for both AGP versions.

**Comment by Oppong** [comment]
@Lyokone  can i share the repository with you so that you can check what the problem actually is

**Comment by JimmyRamokgopa** [comment]
Hi @g-apparence, were you able to figure out what the problem was?
