### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging don't send push for Sony devices [G3121, G3311]

### ISSUE THREAD

**Issue by marekbojecdeviniti** [firebase/flutterfire#12158]
## Bug report

**Describe the bug**
After fetching fcm token, no notifications is send on specific Sony devices:
G3311 - Android 7.0
G3121 - Android 8.0

### Steps to reproduce

1. Fetch fcm token
2. Manually for testing purpose send notification for that specific device
3. Nothing happens

### Expected behavior

Recieve notification

---

## Additional context

 I have tested this on OnePlus 6T and everything works fine so this is a specific Sony issue

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

---

**Comment by darshankawar** [comment]
@marekbojecdeviniti 
Since it seems to be specific to Sony and not on other Android devices, I don't think this would be actionable from plugin side. I suggest you to reach out to [Firebase support](https://firebase.google.com/support/troubleshooter/fcm) for further resolution.
Closing from here. If you disagree, write in comments and I'll reopen it.
