### ISSUE TITLE
🐛 [flutter_auth_web] Support `web` package v0.5.0

### ISSUE THREAD

**Issue by davidmigloz** [firebase/flutterfire#12353]
Hello team,

The current constraints in `flutter_auth_web` for the `web` package are:
https://github.com/firebase/flutterfire/blob/376310f3437476b249e1461ac7a64cbcc1abe943/packages/firebase_auth/firebase_auth_web/pubspec.yaml#L22

Which don't support the latest version of the `web` package ([0.5.0](https://pub.dev/packages/web/changelog#050)) and, consequentially, the latest version of the `http` package ([1.2.1](https://pub.dev/packages/http/changelog#121)).

Thanks for your work!

**Comment by darshankawar** [comment]
This will probably help to resolve https://github.com/flutter/flutter/issues/143575#issuecomment-1948471516

/cc @Lyokone

**Comment by Lyokone** [comment]
Hi @davidmigloz,
I think you can use `dependency_overrides` if you want to force `http` 1.2.1. But the web package version is tied to the Flutter stable version.

**Comment by davidmigloz** [comment]
Make sense, thanks. Hopefully, the next Flutter stable version will bump it to 0.5.0.

For reference:
https://github.com/flutter/flutter/blob/1a7a0618a71857278dc236544e3e1269d05eaa49/packages/flutter/pubspec.yaml#L31

**Comment by ThomasAunvik** [comment]
Mentioning that this is also an issue on `firebase_core_web (2.11.4)`.

**Comment by JgomesAT** [comment]
any schedule to add the package web 0.5.0 to the firebse core web?

**Comment by ThomasAunvik** [comment]
Regarding `firebase_core_web`, it seems it isn't a straightforward package override. Since that package uses `web.TrustedTypePolicy`, `web.TrustedTypePolicyFactory`. `web.TrustedScriptURL` and `web.TrustedTypePolicyOptions` directly, and I believe it is gone from web 0.5.0.

https://github.com/firebase/flutterfire/blob/f24d0a76ff384cf40605ae59af705b2854e53ba7/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L104-L136

and

https://github.com/firebase/flutterfire/blob/f24d0a76ff384cf40605ae59af705b2854e53ba7/packages/firebase_core/firebase_core_web/lib/src/interop/package_web_tweaks.dart#L16-L38

I've opted to forking it temporarely, removing those usages, https://github.com/ThomasAunvik/flutterfire/commit/00ef68513d88296cdb5c7cd43b5b1b673c82a48c, which you can put it in `dependency_overrides`

**Comment by nilsreichardt** [comment]
This issue is blocked by the [`web`](https://pub.dev/packages/web) package because the version `0.5.0` doesn't support `TrustedTypePolicyFactory` and `TrustedTypePolicy `, which are used in `firebase_core`.

@kevmoo already created a PR (#173) for this, which was merged two weeks ago. However, the Dart team hasn't released a new version for `web` which would include the required changes.

As a you workaround, you can overwrite the `web` dependency to use the latest commit (https://github.com/dart-lang/web/commit/d96c01d2252372c9e0fa7ffa52d2d1df331c248b) of the `web` package:

```yaml
dependency_overrides:
  # Is required to be able to build the app using Flutter 3.19. Can be removed
  # when firebase_core uses web >= 0.5.1.
  web:
    git:
      url: https://github.com/dart-lang/web/
      ref: d96c01d2252372c9e0fa7ffa52d2d1df331c248b
```

**Comment by kevmoo** [comment]
@nilsreichardt – keep in mind, you can ALWAYS just copy-paste code to get yourself unblocked.

All of the types are erased. Just be careful about imports so you don't get name collisions when the feature DOES land.
