### ISSUE TITLE
🐛 firebase_auth  Users Not Receiving OTP

### ISSUE THREAD

**Issue by stdSheraz** [firebase/flutterfire#12366]
Addressing Firebase Phone Authentication OTP Delivery Issues: Users Not Receiving OTP

The majority of users successfully receive the one-time passwords (OTPs) that I send out. However, there is a subset of users who do not receive the OTPs, despite the SDK responsible for handling the OTP delivery process not throwing any errors.

**Comment by danagbemava-nc** [comment]
Hi @stdSheraz, have you tried reaching out to firebase support to see if they can help? The plugin does not control delivery of the otps. This is done by the firebase backend. 

Considering some otps are being delivered for some but a subset of your users are not receiving them, this means it is not an issue with the plugin. 

I'll be closing this since the plugin can't control who gets and who doesn't get messages. If you reach out to firebase support and are redirected here, kindly leave a comment below and I will reopen this. 

Thank you
