### ISSUE TITLE
🐛 [firebase_messaging_web] depends upon older version of js which is 3 years old and it's causing incompatible issues with other plugins.

### ISSUE THREAD

**Issue by abdullah432** [firebase/flutterfire#12446]
When I try to use `firebase_messaging_web` and `flutter_native_splash` plugins at one project, I'm getting incompatible error.

`firebase_messaging_web 3.6.7 depends on js ^0.6.3, and because flutter_native_splash >=2.3.12 depends on js ^0.7.1, firebase_messaging_web ^3.6.7 is incompatible with flutter_native_splash >=2.3.12.`

firebase_messaging_web needs to be updated to latest `js` version.

**Comment by Lyokone** [comment]
We are in the process of migrating to using the new `web` which is part of the new Dart versions, see here for the messaging PR:  https://github.com/firebase/flutterfire/pull/12223

Once all the plugins have been migrated we will remove the JS dependency.

Closing since it's already being done on other PRs
