### ISSUE TITLE
[cloud_firestore] Retrieving a document from cache that doesn't exist throws an exception

### ISSUE THREAD

**Issue by eli1stark** [firebase/flutterfire#12521]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Android, iOS

### Description

This is a continuation of this issue: https://github.com/firebase/flutterfire/issues/10887.

Instead of throwing an error, `get` should return an empty document.

### Reproducing the issue

1. Install `cloud_firestore` version `4.14.0`.
2. Install `firebase_core` version `2.24.2`.
3. Ensure you have properly initialized Firebase before calling the `get` method.
4. Make sure that you have enabled Firestore persistence.
5. Ensure that the document you are fetching does not exist in the cache.
6. It doesn't matter if you are offline or online.
7. Run the code below.

```dart
try {
  final snapshot = await FirebaseFirestore.instance
      .collection('name')
      .doc('id1')
      .get(const GetOptions(source: Source.cache)); // throws the error

  // Unreachable code below:
  final json = snapshot.data();

  print(snapshot.exists); // should be false
  print(json); // should be null
} catch (e) {
  // [cloud_firestore/unavailable] The service is currently unavailable. 
  // This is a most likely a transient condition and may be corrected by
  // retrying with a backoff.
}
```

### Firebase Core version

2.24.2

### Flutter Version

3.16.7

**Comment by russellwheatley** [comment]
This is expected behaviour. If you try to get a document that does not exist in cache, it throws an exception. If you try to query a collection in cache that has no results, it won't throw an exception, it will return 0 documents.

Here is the [android documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/Source?_gl=1*nj5eu6*_up*MQ..*_ga*MjQ1NzQ4NzYzLjE3MTExMDQwMjU.*_ga_CW55HF8NVT*MTcxMTEwNDAyNS4xLjAuMTcxMTEwNDAyNS4wLjAuMA..#CACHE) stating this

[apple documentation](https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Enums/FIRFirestoreSource?_gl=1*1yn3ji8*_up*MQ..*_ga*MTcyMjcwMjk4Ni4xNzExMTAzMzk5*_ga_CW55HF8NVT*MTcxMTEwMzM5OC4xLjAuMTcxMTEwMzM5OC4wLjAuMA..#firfirestoresourcecache) stating the same thing.
