### ISSUE TITLE
[Analytics]: Enable debug mode when using Flutter on a Mac when testing a Mac App

### ISSUE THREAD

**Issue by stephane-archer** [firebase/flutterfire#12651]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

macOS

### Description

I tried everything I could find on the internet. I can't Enable debug mode when using Flutter on a Mac when testing a Mac App. Can you check if it works for you and how are you able to enable it? 

### Reproducing the issue

any app with firebase analytics that work on mac should do the job 

### Firebase Core version

2.19.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by russellwheatley** [comment]
@stephane-archer - Open your macOS project in Xcode:

```bash
cd macos
xed .
```

The above open project in Xcode. 

Now add `-FIRDebugEnabled` to your [command line arguments](https://firebase.google.com/docs/analytics/debugview?_gl=1*773sjv*_up*MQ..*_ga*MTM5NzEwMTkwMS4xNzEzMjY0MDMx*_ga_CW55HF8NVT*MTcxMzI2NDAzMS4xLjAuMTcxMzI2NDAzMS4wLjAuMA..#enable_debug_mode)

Run the app from Xcode (rather than via Flutter CLI). Unfortunately, there is no way of running Analytics debug mode from Flutter. It has to be from Xcode because you need the command line argument. See: https://github.com/firebase/flutterfire/issues/11780

**Comment by stephane-archer** [comment]
Thanks a lot @russellwheatley, it finally works. I was adding `-FIRDebugEnabled` to the command line arguments but was using `flutter run` for testing.
I wish it was explained in the documentation that it has to be run from Xcode. 
I hope #12650 can fix this for others.
