### ISSUE TITLE
🐛 [cloud_firestore] Expose VectorValue

### ISSUE THREAD

**Issue by jellynoone** [firebase/flutterfire#13299]
## What feature would you like to see?
Support for VectorValue has landed in native client libraries:

**Web**
Available since `10.13`
- https://github.com/firebase/firebase-js-sdk/releases/tag/firebase%4010.13.0
- https://github.com/firebase/firebase-js-sdk/pull/8215
- https://firebase.google.com/support/release-notes/js#cloud-firestore

**iOS**
Available since: `11.1.0`
- https://github.com/firebase/firebase-ios-sdk/releases/tag/11.1.0
- https://github.com/firebase/firebase-ios-sdk/pull/13404
- https://firebase.google.com/support/release-notes/ios#cloud-firestore

**Android**
Available since: `33.2.0`
- https://firebase.google.com/support/release-notes/android#firestore_v25-1-0
- https://github.com/firebase/firebase-android-sdk/pull/6154

**Comment by jellynoone** [comment]
@Lyokone Are there any plans to support this in the near future? I'm looking to add vectors to existing documents, but cannot since the app crashes due to the vector type not being recognised by the client.

**Comment by Lerobindesbois** [comment]
Same goal as @jellynoone ,  I have real-time listeners from snapshot and it is incompatible, the vector field feature is useful for intelligent searches and blocks an AI application advancement, Almost all developers use STREAM on Firestore like me. since September it is in plan. When do you think you will make this available seriously ??? please can you prioritize this feature

**Comment by Lyokone** [comment]
Hello, VectorValue is now exposed in the latest version of cloud_firestore (you also need to update firebase_core).
PR here: https://github.com/firebase/flutterfire/pull/16476
