### ISSUE TITLE
🐛 [flutterfire] Add Linux platform support

### ISSUE THREAD

**Issue by soufianebenyaala** [firebase/flutterfire#16885]
# What feature would you like to see?
I would like to see FlutterFire plugins add support for the Linux platform. This enhancement would allow developers to build applications that leverage Firebase services on Linux, enabling cross-platform compatibility and expanding Flutter's reach.

## Why would it be useful?
Adding Linux support would:
1. Enable developers to target a wider range of platforms with their Flutter apps.
2. Provide parity with other supported platforms (e.g., iOS, Android, Web).
3. Leverage Firebase's capabilities (e.g., authentication, cloud storage, and Firestore) in desktop environments where Linux is widely used.

**Comment by SelaseKay** [comment]
Hi @soufianebenyaala, FlutterFire is a wrapper around Firebase's native SDKs as far as I know. Since Firebase does not provide a native SDK for Linux, we can't directly support Linux through FlutterFire. We recommend raising a feature request with [Firebase Support](https://firebase.google.com/support).
