### ISSUE TITLE
[📚] Broken links on documentation website. Including sign-in methods links and error-handling link.

### ISSUE THREAD

**Issue by yashwanth-ravula** [firebase/flutterfire#6751]
https://firebase.flutter.dev/docs/auth/usage/#other-sign-in-methods
Links(eg: Google Sign-In, Phone Number Sign-In,...) of **Other sign-in methods** are pointing to 'Page Not Found'.

**Comment by markusaksli-nc** [comment]
@Ehesp This again https://github.com/FirebaseExtended/flutterfire/issues/4696

**Comment by markusaksli-nc** [comment]
Specific links in social auth also broken https://github.com/FirebaseExtended/flutterfire/issues/7013

**Comment by ankurg132** [comment]
Can I fix this? Seems like https://firebase.flutter.dev/docs/auth/social/#google is the correct link instead of https://firebase.flutter.dev/docs/auth/social#google at which it is redirecting to currently. (Same for other methods too)

**Comment by darshankawar** [comment]
Since [https://firebase.flutter.dev/docs](https://firebase.flutter.dev/docs/auth/social/#google) domain has been archived and moved to firebase.google.com as mentioned below:

<img width="1000" alt="Screenshot 2022-06-29 at 4 50 39 PM" src="https://user-images.githubusercontent.com/67046386/176425050-4b29657a-6ac7-4390-8d30-ccc88a6592e9.png">

I suggest you to now follow the new link https://firebase.google.com/docs/auth/flutter/federated-auth for future reference.

Closing.
