### ISSUE TITLE
[firebase_crashlytics] File names are incorrect on Android (still an issue?)

### ISSUE THREAD

**Issue by carman247** [firebase/flutterfire#6925]
Pretty sure this is still an issue ...

https://github.com/FirebaseExtended/flutterfire/issues/80

If not, which version was it fixed in, or what needs to be done differently to prevent recording errors in .java files?

I'm using: firebase_crashlytics: ^2.0.6

**Comment by markusaksli-nc** [comment]
Hi @carman247 
Could you please try upgrading to the latest `firebase_crashlytics: ^2.2.1`?
Thank you

**Comment by carman247** [comment]
> Hi @carman247
> Could you please try upgrading to the latest `firebase_crashlytics: ^2.2.1`?
> Thank you

Ok, will upgrade and report back

**Comment by carman247** [comment]
I've tested using 2.2.1 in release mode and still getting errors reported as java files instead of dart.

**Comment by markusaksli-nc** [comment]
Seeing this as well. Since https://github.com/FirebaseExtended/flutterfire/issues/80 is locked this can be tracked here as a continuation.

**Comment by russellwheatley** [comment]
@carman247, are you able to provide steps to reproduce this behaviour? Perhaps in the `firebase_crashlytics/example` project. I'm seeing dart file extensions in my crash reports.
 
<img width="506" alt="Screenshot 2021-09-14 at 16 10 16" src="https://user-images.githubusercontent.com/16018629/133273481-4cd73e26-6964-4c6c-bb6f-cb154d3fbf46.png">

**Comment by zaralockheart** [comment]
The project I am working on is using
```
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
```

and one example I copy from crashlytics is (with some code change due to pnc)

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at State.context(State.java:1095)
       at _EntryPage.initState.<fn>(initState.java:33)
       at Utils.afterBuild.<fn>(afterBuild.java:94)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1144)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1090)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:998)
```

**Comment by carman247** [comment]
I have also updated my project from fabric to firebase .. I'll try and get some more information added today about how I am implementing crashlytics/firebase.

Could updating from fabric to crashlytics, and some lingering references be what's causing the problem?

**Comment by bounty1342** [comment]
Hi @russellwheatley, 

Following your recommendation I tested the firebase_crashlytics/example.

**Works on debug mode :**
![image](https://user-images.githubusercontent.com/6307253/135699637-1129d74b-83c5-4db2-90aa-82489e76021e.png)

**but NOT on release :**
![image](https://user-images.githubusercontent.com/6307253/135699561-e005744d-65a4-4ce2-a2c7-7bea05d215cf.png)

Debut mode show correct class and ligne number :
![image](https://user-images.githubusercontent.com/6307253/135699942-3b459a5a-e971-474a-a544-972b675989b6.png)

Release mode show correct line number but no class and replace 'dart' with 'java' (Other crash may differ more)
![image](https://user-images.githubusercontent.com/6307253/135699910-5c2f3aec-061d-459b-a498-c6657ea02c82.png)


```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/bounty1342/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (30 hours ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
```
```
  firebase_crashlytics: ^2.2.2
  firebase_core: ^1.7.0
```

This is certainly why there is also issues with obfuscation.
This is a really annoying issue.

**Comment by bounty1342** [comment]
`flutter build appbundle --release --obfuscate --split-debug-info=build/app/outputs/symbols
`
produce obfuscated code that Firebase can't handle:
![image](https://user-images.githubusercontent.com/6307253/135700497-a1c9b625-16eb-4e10-86a4-aa06ddca16a1.png)

Previous issue similar to this :
https://github.com/FirebaseExtended/flutterfire/pull/4407

Btw on @untp screenshot it also show java classes instead of dart:  
https://github.com/FirebaseExtended/flutterfire/pull/4407#issuecomment-815945809

https://github.com/FirebaseExtended/flutterfire/pull/4407#issuecomment-815605757This PR explain why the .java behavior but it should be made clear on the docs as a warning. (People expect dart file and I was confuse to see those java...)

Finally, the PR regex dosent seem to match with this :
`. #00 abs 0 virt 00000000001cb0af _kDartIsolateSnapshotInstructions+0xe660f (.java)`

Hopefully i'm wrong, but it seems the previous PR was incomplete. Hope this help.

Regards

**Comment by untp** [comment]
I reproduced the issue above where it worked in debug but not in release.

I used this simple code (and copied [firebase_crashlytics/lib/src/utils.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart) to project directory for testing `getStackTraceElements`):
```dart
import 'dart:async';
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';

import 'utils.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseCrashlytics.instance.recordError('Error object', StackTrace.current);
  print(jsonEncode(getStackTraceElements(StackTrace.current)));
}
```

Debug mode:
![](https://user-images.githubusercontent.com/54450843/135710916-306cc941-3158-4516-9770-1edebf37d549.png)

Release mode:
![](https://user-images.githubusercontent.com/54450843/135710952-42312748-811b-4e5e-9f26-bed09d5a476b.png)

Obfuscated release mode:
![](https://user-images.githubusercontent.com/54450843/135710965-68c5d81c-ee2b-4832-ae00-6932601fc18e.png)
Deobfuscation: `#0      main (package:crashlytics_example/main.dart:13:71)`

`print(jsonEncode(getStackTraceElements(StackTrace.current)))` output:
Debug mode: `[{"file":"package:crashlytics_example/main.dart","line":"14","method":"main"}]`
Release mode: `[{"file":"package:crashlytics_example/main.dart","line":"14","method":"main"}]`

Json encoded getStackTraceElements returns same output both in debug and release. So the problem is not caused from this package. It is probably in the backend.

Deobfuscation can be done with https://github.com/FirebaseExtended/flutterfire/issues/2644#issuecomment-746217634.
I also filed an issue to dart sdk (dart-lang/sdk#47357), so we can directly deobfuscate without editing any lines.

**Comment by bounty1342** [comment]
It hard to keep deobfuscing by hand for apps in production.
Is there any configuration that will prevent this issues or alternative setup ?

On top of it, every version produce a new set of error, and have to switch better symbols...
This make Crashlytics unfit for production app atm...

**Comment by 4ntoine** [comment]
Any update on this?

**Comment by russellwheatley** [comment]
@4ntoine - I'm still in communication. Will update when I have something to report.

**Comment by russellwheatley** [comment]
Quick update - Firebase support was able to reproduce and will look to get this fixed. I was told to keep an eye out for future releases/release notes 👌

**Comment by russellwheatley** [comment]
Hey folks, I haven't noticed anything in the release notes, but I believe this issue has now been resolved. Could someone please confirm that the correct file extension is now displayed in the Crashlytics console, please 🙏 ?

**Comment by 4ntoine** [comment]
Still having the issue

**Comment by bounty1342** [comment]
This one should stay open.

@russellwheatley, can you check with Firebase support what's the exact status for this issue on their side ? 

Thanks

**Comment by russellwheatley** [comment]
@bounty1342 reopened. Firebase support said to keep an eye on release notes for changes in status. No changes so far I'm afraid.

**Comment by Lyokone** [comment]
Since version `2.9.0` this should not be an issue anymore:
```
FEAT: Send Flutter Build Id to Crashlytics to get --split-debug-info working
```

Please reopen if needed.
