### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.onMessageOpenedApp.listen((message){} triggering more than once

### ISSUE THREAD

**Issue by pranav-asthi** [firebase/flutterfire#7243]
FirebaseMessaging.onMessageOpenedApp.listen((message){} triggering more than once for a single notification

**Comment by MagTuxGit** [comment]
I don't know if related. I get onMessageOpenedApp called on app start from terminated state.
![Screenshot 2021-11-10 at 08 43 27](https://user-images.githubusercontent.com/5296407/141063805-938a1e1e-90c4-46b0-8749-b2fb83393627.png)

**Comment by Vov4yk** [comment]
Faced the same issue. 
Thing is there should be overlapping of `getInitialMessage` and `onMessageOpenedApp` stream due documentation. But it happens when app is opened from terminated state.
From messaging.dart:
`
  /// Returns a [Stream] that is called when a user presses a notification message displayed
  /// via FCM.
  ///
  /// A Stream event will be sent if the app has opened from a background state
  /// (not terminated).
  ///
  /// If your app is opened via a notification whilst the app is terminated,
  /// see [getInitialMessage].

  static Stream<RemoteMessage> get onMessageOpenedApp =>
      FirebaseMessagingPlatform.onMessageOpenedApp.stream;

`

**Comment by vincepunkrock** [comment]
I had the same problem, also with FirebaseMessaging.onMessage.listen.

I fixed it by putting the StreamSubscription<RemoteMessage> return by the listen function in a variable. Then, before I call FirebaseMessaging.onMessage.listen, I check if the subscription already has been set, if yes, I don't make the call. 

if(_onMessageSub == null) {
      _onMessageSub = FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        print("Notification received when app is in the foreground");
        _handlePushNotificationPayload(message);
      });
}

Otherwise, it seems that the call to .listen creates multiple subscriptions and in my case it was triggered up to 6 times.
I'm not sure if it's the right way to go about it, but it seems to solve the problem. Maybe the example on pub.dev should be updated?

**Comment by abigotado** [comment]
> I had the same problem, also with FirebaseMessaging.onMessage.listen.
> 
> I fixed it by putting the StreamSubscription return by the listen function in a variable. Then, before I call FirebaseMessaging.onMessage.listen, I check if the subscription already has been set, if yes, I don't make the call.
> 
> if(_onMessageSub == null) { _onMessageSub = FirebaseMessaging.onMessage.listen((RemoteMessage message) { print("Notification received when app is in the foreground"); _handlePushNotificationPayload(message); }); }
> 
> Otherwise, it seems that the call to .listen creates multiple subscriptions and in my case it was triggered up to 6 times. I'm not sure if it's the right way to go about it, but it seems to solve the problem. Maybe the example on pub.dev should be updated?

@vincepunkrock Could you please share a bit more code? Does the subscription prevent multiple calls?

**Comment by Bhagat8533** [comment]
@abigotado Here how I have fixed this issue for me

**Comment by abigotado** [comment]
@Bhagat8533 Thank you very much!

**Comment by russellwheatley** [comment]
Hey @pranav-asthi, which platform are you experiencing this on?

**Comment by pranav-asthi** [comment]
i fixed it a long time ago and i forgot to close this issue
