### ISSUE TITLE
[📚] Storage Api with signed urls for puts/gets

### ISSUE THREAD

**Issue by cyberpwnn** [firebase/flutterfire#7606]
It wasn't mentioned anywhere in the documentation, about uploading / downloading with signed urls, So I assume it's not supported. I did notice the `FirebaseStorage.instance.refFromURL(actualUrl)`, however looking at the source, it doesnt take into account the actual signature, it just reads the bucket & path.

I'm not sure how to go about this other than directly writing my own puts, however looking at the actual api, I'd love to use the already existing UploadTask & multipart backend firebase already has, Would it be possible to either document a good way to upload from a signed url in flutter, or perhaps it would be simple enough to support signed urls.

### Additional Context
I have dynamic documents created by users & shared by users, so they have their own ids with access levels each. Since you cant read documents from storage rules, and the auth custom claims api restricts you to 1kb (firebase uses 600b out of that) I cant use claims either. My final attempt is by using signed urls for temporary upload access granted by a cloud function, however I'm weary on writing my own http post requests for the uploads because I need to support web also (cors & all), that and i'm not too familiar with how gcloud bucket apis work.  

Perhaps someone more involved in the gcloud space / firebase apis might know a clean solution for this? Thanks!

**Comment by ABleas** [comment]
Just registering my interest since I recently wanted to do this.

Although, I'm using http requests to the REST API to send files directly, as a work-around.

**Comment by yamauchieduardo** [comment]
I really need this improvement.

In my project I stored the `file-url` to share files with another users. Plus, I restricted the storage rules to `get` the files just for authenticated users, this approach is useful because block unauthenticated users. 

In counterpart, I unable to use some plugins like the [Network to file image](https://pub.dev/packages/network_to_file_image) to download the files, because plugins usually use http/https to get/put files (the rules block the requests).

Sinned urls could very useful to allow this type of interaction, between the plugins that uses http/https requests and the Storage with rules that require some type of authentication.

**Comment by russellwheatley** [comment]
Hey @cyberpwnn, this kind of feature request is relevant for the underlying SDKs that FlutterFire wraps around. You should raise issues on the [iOS SDK](https://github.com/firebase/firebase-ios-sdk) & [Android SDK](https://github.com/firebase/firebase-android-sdk). Although I do wonder why it's possible on the admin SDK (server side) but not on the client SDKs. There might be a security concern.
