### ISSUE TITLE
🐛 [flutterfire_ui] SignInScreen not usable through integration tests

### ISSUE THREAD

**Issue by fodil-a** [firebase/flutterfire#7930]
## Bug report

**Describe the bug**
When writing integration tests, I need to go through the AuthGate, but I can't target the EmailInput field or PasswordInput field.
Making it impossible to test, and then to use !

### Expected behavior

I expect both EmailInput and PasswordInput to have keys.

**Comment by fodil-a** [comment]
I have a quickfix where I put keys on a fork, but could be better if we get keys to use

**Comment by darshankawar** [comment]
@fodil-a 
By `I need to go through the AuthGate`, do you mean the native dialog box that asks you to enter your email and password ?
That seems to be coming from native and not Flutter and when you are using `integation_test`, I think it still doesn't interact with native UI elements.
See this similar issue: https://github.com/flutter/flutter/issues/86295 and you may need to track it in this issue because it's not flutterfire_ui issue but underlying integration_test package's current limitation.

**Comment by fodil-a** [comment]
I try to use the 'SignInScreen', which is a flutter widget from your UI library (not native), I forked the project, added 2 keys, and now my integration tests work.

**Comment by fodil-a** [comment]
This one https://github.com/FirebaseExtended/flutterfire/blob/master/packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart

**Comment by darshankawar** [comment]
I see. Thanks for the details.

**Comment by workerbee22** [comment]
Yes please keys so we can more easily integration test 👍

**Comment by lesnitsky** [comment]
Adding a whole bunch of properties just to pass keys down. the widget tree would be very cumbersome and pollute constructor arguments. Instead you can used [find.byType()](https://api.flutter.dev/flutter/flutter_test/CommonFinders/byType.html)
