### ISSUE TITLE
🐛 [firebase_analytics] Android: Does not work with dart only initialization of firebase, ios works

### ISSUE THREAD

**Issue by neiljaywarner** [firebase/flutterfire#8098]
Expected: Events can be uploaded to Google Analytics
Actual: iOS works, Android does not (even after delay, even with debug enabled, etc)
--- getting E/FA      ( 5950): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

- The documentation page for cli has a "? indicating it works but behaviour is different. There is no link explaining that different behaviour means iOS broken
- Analytics in firebase in my opinion is so common that  imho dart only initialization should definitely not be the recommended way until this is fixed.

**Comment by neiljaywarner** [comment]
@darshankawar I understand that the docs give a '?' but say 'Indicates your app will build and run but plugin behavior may be different.' but if it doesn't work there should be
1a) a link for the question mark clarifying like hte other question marks
1b) an X for Android since it doesnt' work at all
2) this issue escalated bc flavors and bc analytics very high usage.
see https://github.com/FirebaseExtended/flutterfire/issues/7639

**Comment by darshankawar** [comment]
@neiljaywarner 
Thanks for the report and feedback. I looked at the PR again which fixed the original issue: https://github.com/FirebaseExtended/flutterfire/issues/7639.

The PR added following section:

<img width="1152" alt="Screenshot 2022-02-17 at 4 45 29 PM" src="https://user-images.githubusercontent.com/67046386/154471113-c62151d3-b8d4-47f3-a2bf-8991fc17bdde.png">


Looking at it, `analytics` for `Android` is X, but somehow in the CLI document, it shows up as `?` which could be the cause of confusion.

<img width="842" alt="Screenshot 2022-02-17 at 4 51 21 PM" src="https://user-images.githubusercontent.com/67046386/154471323-3f0668ac-35b3-4240-a7ef-69a98619c794.png">

Also, not sure, but `X` in the PR fix also seems to be showing up as `?` for other plugin status too. 

I'll keep this open for further insights to know if `?` need to be updated as X to show clear and correct status.

/cc @pr-Mais since you fixed and added the document part.

**Comment by pr-Mais** [comment]
Analytics on Android has issues with Dart-only initialization, but the app compiles that's why the question mark is used instead. Crashlytics has links because there is further platform integration that is required, but in case of Analytics on Android, there isn't any, just fallback to the manual installation temporarily until all issues are resolved.

**Comment by krishnashetty0** [comment]
Hi, when will Analytics on Android be supported with with Dart-only initialization? 
Is there any alternative to Analytics which we can use in Flutter app? 

For me only Dart-only initialization works(manual initialisation doesn't work). And I need Analytics is there any workaround?

**Comment by neiljaywarner** [comment]
@darshankawar  any update please?

**Comment by adg-mh** [comment]
Does anyone know the status on this?

**Comment by neiljaywarner** [comment]
@darshankawar the entire table is gone making it seem like everything is fixed, but I think my colleague says that it still doesn't work. any update?

**Comment by neiljaywarner** [comment]
@puf  @darshankawar @RedBrogdon this should definitely be fixed after i/o announcing flutter is first class citizen with firebase right?

**Comment by carlosfiori** [comment]
There is nothing in the new docs about this right?

**Comment by darshankawar** [comment]
Please check [this](https://firebase.google.com/docs/analytics/get-started?platform=flutter) new document and see if it helps.

**Comment by TheCarpetMerchant** [comment]
@darshankawar The link provided doesn't help.
Personally, I followed [this doc](https://firebase.google.com/docs/flutter/setup) and it works perfectly for crashlytics, but not analytics. Which is really weird, honestly.
Moreover, said doc specifies that analytics is supposed to work and need to be amended : 
![image](https://user-images.githubusercontent.com/5080204/172049314-41464027-b8e2-4afe-9af0-a8c17c83200e.png)

**Comment by RedBrogdon** [comment]
CC @ericwindmill

**Comment by Charlinjoeaht** [comment]
I agree to @TheCarpetMerchant. The document says it supports android.
These documentation are confusing. I have not seen any other document. If there are any please share those documents too.

When will you start supporting dart only initialisation?

**Comment by Charlinjoeaht** [comment]
@darshankawar Please ask the team to fix this issue to support Dart-only initialisation on Android as soon as possible

If there are any workaround without going for manual installations, they are welcome too. This is really taking out our time

**Comment by russellwheatley** [comment]
Please install the latest FlutterFire CLI (`dart pub global activate flutterfire_cli`) and run `flutterfire configure`, it will write the config files for android & iOS. We've experienced issues where some Firebase products still expect the config files to be used during runtime. 

You can still also pass in the FiresbaseOptions (needed for web platform) as default Firebase app will always initialize from config files first.

**Comment by Charlinjoeaht** [comment]
I have Apps with Flavors. Each flavors has different firebase configuration. Current solution is not working for Apps with Flavors. This solution works only for the app with one android configuration and one ios configuration
