### ISSUE TITLE
flutterfire_ui 0.4.0 Google Sign In Error on Android and macOS desktop

### ISSUE THREAD

**Issue by Splashman777** [firebase/flutterfire#8384]
I upgraded flutterfire_ui from 0.3.6+1 to 0.4.0 and Google Sign In button no longer works. It always says "An unknown error occurred". I can't find anything in the logs for further info. Switched back to 0.3.6+1 and it works fine.

The only thing I could find while debugging was this: "com.google.android.gms.common.api.ApiException: 10: null". Sounds like I might have something set up wrong but I've only had a problem with this version so I'm confused.

**Comment by tomoyuki28jp** [comment]
Facing the same issue. I get `400: redirect_uri_mismatch` error.

**Comment by MesharSuliman** [comment]
> yes
> ![Screen Shot 1443-09-03 at 1 13 45 AM](https://user-images.githubusercontent.com/94109963/161459920-709db85b-4b58-4560-9296-7fc62ebb3981.png)

I have the old version
It has no problems with google sign in

**Comment by MesharSuliman** [comment]
> I upgraded flutterfire_ui from 0.3.6+1 to 0.4.0 and Google Sign In button no longer works. It always says "An unknown error occurred". I can't find anything in the logs for further info. Switched back to 0.3.6+1 and it works fine.
> 
> The only thing I could find while debugging was this: "com.google.android.gms.common.api.ApiException: 10: null". Sounds like I might have something set up wrong but I've only had a problem with this version so I'm confused.
![Screen Shot 1443-09-03 at 5 05 57 AM](https://user-images.githubusercontent.com/94109963/161462755-2b79260d-9238-4727-ad80-f6f721389f6d.png)

**Comment by MesharSuliman** [comment]
The solution //
![Screen Shot 1443-09-03 at 5 29 40 AM](https://user-images.githubusercontent.com/94109963/161464306-8e140e24-0322-4ec8-b19a-3bf48d5f9b7d.png)

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same using latest version.

/cc @lesnitsky

**Comment by lesnitsky** [comment]
@Splashman777 what platform are you experiencing this issue?

**Comment by MesharSuliman** [comment]
‫Macos

**Comment by talkbiz** [comment]
I have similar issue on MacOS for both Google and Apple sign in.

**Comment by maks** [comment]
Strangely I'm getting the same "an unknown error has occurred" error message and I *haven't* moved off `0.3.6+1` but simply added the `google_sign_in` package, where previously I was only using email/password logins (which still work fine).

**Comment by workerbee22** [comment]
Also getting an 'An unknown error occurred' with `google_sign_in` ^5.3.0 and `flutterfire_ui` ^0.4.0+2. 

This occurs when Login with Google, pick a Google account and then on the FlutterFire UI screen returns.

**Comment by lesnitsky** [comment]
I'm looking into it

**Comment by etienn01** [comment]
I encountered the same issue on Android after upgrading `flutterfire_ui` from `0.3.6+1` to `0.4.0+5`.

[This change](https://github.com/firebase/flutterfire/commit/7edbf5e692499feb7b3c1b29dab67479917df21f#diff-aa7c72a62221edb5c71ce538563b9443afc22914fa0585ff2ede255877ff8885R30) may be the reason. The `clientId` parameter is now passed to the `GoogleSignIn` constructor, and because my `GoogleProviderConfiguration` uses the `androidClientId` value, it doesn't work. Hardcoding the web clientId value fixes the issue (it's actually what's specified in the [docs](https://github.com/firebase/flutterfire/blob/master/packages/flutterfire_ui/doc/auth/configuring-providers.md#google)), but on the other side, the docs of `GoogleSignIn.clientId` states that it is "Only supported on web".

**Comment by workerbee22** [comment]
@etienn01 Specifying the `clientId` does not work for me.

I'm using `google_sign_in` ^5.3.1 and `flutterfire_ui` ^0.4.0+5
I always have included the hard coded web `clientId` with my `GoogleProviderConfiguration` as well, because yes as you point out it has always said to use this clientId.

But still get the "An unknown error occurred".

**Comment by 7AveNooN7** [comment]
I have the same issue. Google SignIn button works only with version of flutterfire_ui smaller than 4.0.0. In other case 'An unknown error occured' happens. IDE: Android Studio, google_sin_in: 5.3.0

**Comment by prgtrdr** [comment]
> 
Same issue here when debugging on older Samsung SM-G900V running Android 6.0.1. Same project runs on iPhone and iPad with no problems with Sign in with Google.

**Comment by wstrange** [comment]
Shot in the dark here, but does this line:

https://github.com/flutter/plugins/blob/5712aedbc5d1ad588056fd8ad7d947d5e39be85c/packages/google_sign_in/google_sign_in_ios/lib/google_sign_in_ios.dart#L28


Need to include "profile" in the default scopes?

**Comment by workerbee22** [comment]
Update which shows we have a clear conflicting requirements around the id. 

Trying to use `SignInView` I currently specify in my Google Provider Configs the `clientId` because it is required. 

I'm using the latest:

`google_sign_in` ^5.4.0
`flutterfire_ui` ^0.4.3

Result when the app runs on Android is this warning:
`W/google_sing_in(13914): clientId is not supported on Android and is interpreted as serverClientId.Use serverClientId instead to suppress this warning.`

So `clientId` is required by the const `GoogleProviderConfiguration` as part of passing `providerConfigs` to `SignInView`. But problem is that we don't yet have available to us `serverClientId`, although warning says it interprets `clientId` as `serverClientId` ? So kinda confusing.

**Comment by MousyBusiness** [comment]
I've just hit this and I think the warning is a red herring...
Other than the normal 100million cleans, version changes and rebuilds, I did two things that eventually go this working again .
1. APIs & Services > OAuth Consent Screen > Edit app... (There was a new email requirement and my scope were empty, I added  "openid",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile", and matched it in the GoogleProviderConfiguration)
2. Nuked my Android Firebase configuration by deleting the SHA keys and re-inputting. This required a firebase configuration re-run and updated ios and android google configs.

Hopefully one of those two things helps the rest of you (I assume it's the first one). I believe there is a decent delay after changing the OAuth Consent Sceen, so give it an hour
