### ISSUE TITLE
cloud_firestore: ^3.1.9 - The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.

### ISSUE THREAD

**Issue by swarupa-v** [firebase/flutterfire#8414]
I am trying to fetch data from firestore cache in my flutter application and I get the following error.
The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
This is not happening consistently and happens only when offline and fetching data from cache.

Any help will be appreciated.

Flutter version details:
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (5 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

**Comment by darshankawar** [comment]
@swarupa-v 
The error indicates probably an issue at firebase side and not at client's side (i.e flutterfire) so we can't do much about this error since it is not in flutterfire's control. You'll need to check out [this](https://github.com/firebase/flutterfire/discussions/5708) discussion and see if any any of the comments help you to resolve it.
Closing from here as this is not flutterfire plugin issue.
