### ISSUE TITLE
🐛 [firebase_messaging] ANRs in Android

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#8467]
We have some ANRs in the Flutter Android app. So I posted an issue on the Flutter repo and after investigating from there, it seems that the issue is with the `FirebaseMessaging`.
And they suggested putting it here for more debugging.

Referenced issue: https://github.com/flutter/flutter/issues/101886

You can check the ANRs here https://github.com/flutter/flutter/issues/101886#issuecomment-1099097616

**Comment by darshankawar** [comment]
@deepak786 
Looking at the logs you shared, it doesn't seem to be caused by messaging plugin, but due to native Android code and probably due to `FirebaseInstanceIdReceiver` component. 
See below similar / related issues:

https://github.com/firebase/quickstart-unity/issues/1257
https://github.com/firebase/firebase-android-sdk/issues/3052

Hence, I suggest you to open this issue in firebase-android-sdk github. 
Closing from here. If you get redirected here or in flutter repo, please write in respective issues and we'll reopen them if required.
