### ISSUE TITLE
could not find firebase-encoders-proto-16.0.0.jar

### ISSUE THREAD

**Issue by EmelianShkira** [firebase/flutterfire#8484]
when i press on the link it's open it on browser and download the file but on ide show this error without compile the app
![11](https://user-images.githubusercontent.com/46813666/164088523-afb64a8f-814a-4238-ab0c-49f2a4e601ad.jpg)

**Comment by darshankawar** [comment]
@EmelianShkira 
We are not sure which flutterfire plugin are you referring to. When you open an issue, please use new issue [template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough details to work with. 
Closing for now as not enough details provided.
