### ISSUE TITLE
[firebase_remote_config] not advertise react-native 

### ISSUE THREAD

**Issue by pinpong** [firebase/flutterfire#8514]
https://github.com/firebase/flutterfire/blob/master/packages/firebase_remote_config/firebase_remote_config/example/lib/main.dart#L84

**Comment by darshankawar** [comment]
@pinpong 
Can you elaborate on the issue you reporting ? What exactly is the purpose of this issue ?

**Comment by pinpong** [comment]
Seems like the documentation needs an update because it's using a react native config

**Comment by darshankawar** [comment]
@pinpong 
I think it has been since beginning because other flutterfire plugins too uses react-native config which I believe they are actively using to support both flutter and react-native, so I don't think this probably would change.
Closing for now. If you disagree, write in comments and I'll reopen it.
