### ISSUE TITLE
🐛 [firebase_crashlytics] Handler has been deprecated

### ISSUE THREAD

**Issue by bswhite1** [firebase/flutterfire#8577]
## Bug report

**Describe the bug**
Build is throwing warnings. compiling with details shows it is Handler has been deprecated within FlutterFirebaseCrashlyticsPlugin.java

```
/Users/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.7.2/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java:72: warning: [deprecation] Handler() in Handler has been deprecated
    new Handler()

```

### Steps to reproduce

1. Compiled with android studio on mac

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

</details>

---

### Flutter dependencies

using:
  firebase_core: ^1.16.0
  firebase_analytics: ^9.1.7
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14

  firebase_crashlytics: ^2.7.2
  firebase_messaging: ^11.3.0
  firebase_performance: ^0.8.0+11

---

**Comment by russellwheatley** [comment]
Hi, this has been fixed by using a [non-deprecated constructor](https://github.com/firebase/flutterfire/blob/f2e03484f99bd2efcb065d31721b9a2b6e801bf5/packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java#L82) as documented [here](https://developer.android.com/reference/android/os/Handler). Thanks.
