### ISSUE TITLE
🐛 [firebase_auth] How to update phone number on web

### ISSUE THREAD

**Issue by BugsOverBugs** [firebase/flutterfire#8589]
## Bug report

**Describe the bug**
How can I get `PhoneAuthCredentials` from `WebConfirmationResult`?

### Steps to reproduce

1. I want to update the users phone number on web
2. To update the phone number `PhoneAuthCredentials` are needed
4. I can not access the `PhoneAuthCredentials` from `WebConfirmationResult`

### Expected behavior

Is there a way to use `.updatePhoneNumber` on web?

### Sample project
```
if (webConfirmationResult != null) {
  try {
    UserCredential _credential = await webConfirmationResult!.confirm(otp);
    await user!.updatePhoneNumber(_credential); // error: The argument type 'UserCredential' can't be assigned to the parameter type 'PhoneAuthCredential'.
    // Finish
  } catch (e) {
   print(e.toString());
  }
} else {
  // ...
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cloud_firestore 3.1.14 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 3.3.17 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.16.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.2.15 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
```

</details>

---

**Comment by darshankawar** [comment]
@BugsOverBugs 
Check below screenshot and see if it helps.

<img width="846" alt="Screenshot 2022-05-05 at 4 28 14 PM" src="https://user-images.githubusercontent.com/67046386/166910082-c83145fa-57ba-4d63-9113-008628513653.png">

**Comment by BugsOverBugs** [comment]
> @BugsOverBugs Check below screenshot and see if it helps.
> 
> <img alt="Screenshot 2022-05-05 at 4 28 14 PM" width="846" src="https://user-images.githubusercontent.com/67046386/166910082-c83145fa-57ba-4d63-9113-008628513653.png">

This is not the answer I asked for. This is another topic, not my question!

**Comment by russellwheatley** [comment]
Hey @BugsOverBugs, you need to return this [credential](https://github.com/firebase/flutterfire/blob/1f8d79a3ee2ab6e5a73cd57d1ce164bccfe14879/packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/phone_auth.dart#L31).

Here is the [e2e test](https://github.com/firebase/flutterfire/blob/8e95a51d99ffc5fec106d933e46c9f331c1e2d50/tests/test_driver/firebase_auth/firebase_auth_user_e2e.dart#L813-L855) for it (commented out because it is flakey with the emulator).

[Here it is](https://github.com/firebase/flutterfire/blob/8e95a51d99ffc5fec106d933e46c9f331c1e2d50/tests/test_driver/firebase_auth/firebase_auth_user_e2e.dart#L857-L888) used but to test the returned exception. You should be able to get it working from these snippets.

Thanks.
