### ISSUE TITLE
Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called

### ISSUE THREAD

**Issue by Niyazdev** [firebase/flutterfire#8624]
`Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.`

On tapping notifications im getting this warning in IOS.

My delegate file

```
`override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {

        setUpPaymentBridging()

        GeneratedPluginRegistrant.register(with: self)
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
        }

        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    // This method will be called when app received push notifications in foreground
    override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
    {
        if #available(iOS 14.0, *) {
            completionHandler([.banner, .badge, .sound])
        }else{
            completionHandler([.alert, .badge, .sound])
        }
    }`

```

Kindly help.. Been stuck in this for two days now...

**Comment by darshankawar** [comment]
@Niyazdev 
There's not enough details to make this report actionable. When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Currently we don't know what flutter version you are on, what plugin version you are using and didn't provide any reproducible code sample to properly debug this issue, so please provide all requested details.

https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here
