### ISSUE TITLE
🐛 [ firebase_analytics: ^9.0.5 ]Crashing iOS app on startup

### ISSUE THREAD

**Issue by AhkamKhalaaf** [firebase/flutterfire#8634]
app crashes on startup without any error

**Comment by darshankawar** [comment]
@AhkamKhalaaf 
When you open an issue, please use new issue [template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough details to work with.
Closing for now since no details are provided.
