### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ CONFIGURATION_NOT_FOUND ]

### ISSUE THREAD

**Issue by kdhanapriya** [firebase/flutterfire#8636]
i am getting this error. can u guide. but i enable authentication in firebase console too

**Comment by darshankawar** [comment]
@kdhanapriya 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.
See [this](https://stackoverflow.com/questions/65555623/flutter-firebaseexception-an-internal-error-has-occurred-configuration-not) similar SO link and check if it helps. Else, please ask support questions on stackoverflow.
The error indicates configuration is not setup between your app and firebase or is incorrectly done.
