### ISSUE TITLE
🐛 [firebase_auth] phone number login disconnect user and cannot reconnect

### ISSUE THREAD

**Issue by g-apparence** [firebase/flutterfire#8659]
## Bug report

**Describe the bug**
Some users after 2 days being connected are automatically disconnected and cannot reconnect. 
- connection uses phone number authentication
- Android (Having 13 events)
- Sentry reports this error : "FirebaseAuthException: [firebase_auth/session-expired] The sms code has expired. Please re-send the verification code to try again."

### Steps to reproduce

1. Login with android using a phone number
2. stay logged
3. you will be disconnected (token not refreshed)
4. you can't login again with your phone number

### Expected behavior

- User should not be disconnected. 
- User should be able to reconnect using this phone number.

**Comment by darshankawar** [comment]
@g-apparence 
Thanks for the report. Looking at the bug report and case that the user cannot reconnect and can't login again, indicates this could be an issue with firebase tools or native sdk and not with flutterfire auth plugin, since the flutterfire is a wrapper around native sdks and sends and receives data through dart from the server, so the reconnection or unable to login would be handled at server side.
Since the data may not be coming through and hence flutterfire correctly throws the exception `firebase_auth/session-expired] The sms code has expired. Please re-send the verification code to try again."` because it doesn't seem to have received the expected data from server.

I suggest you to reach out to firebase tools or native sdk github for further resolution.

**Comment by g-apparence** [comment]
Hi, 
I think I just found the problem (I can't confirm but this is a good hint). 
We used the auth.currentUser to check if user was authenticated. 
Problem is that it seems not the best way to track user state. I moved this to the listen way. 
I'll confirm if that solves this.

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this behavior ?

**Comment by darshankawar** [comment]
Thanks for the update. Since there doesn't seem to be a concrete reproducible code sample that shows this behavior locally, I'll keep this issue open and label for further insights from the team.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hi @g-apparence, very happy to debug this if you can provide a minimal, reproducible code sample 🙏
