### ISSUE TITLE
[📚] Bring back our docs

### ISSUE THREAD

**Issue by paviln** [firebase/flutterfire#8667]
For what reason has the flutterfire docs have been removed, the new google docs are so confusing. This ruined my day...

**Comment by darshankawar** [comment]
@paviln 
Can you elaborate what's confusing in the new link https://firebase.google.com/docs/flutter/setup?platform=web ? That way we can address this issue better.

**Comment by Hinten** [comment]
I could not find the link for the old cloud_firestore_odm docs also. Where is it?

**Comment by cvanvlack** [comment]
Where is the documentation for: 

- minimum iOS deployment target for a given package
- Documentation listing how to pull recent FirebaseFirestore builds from github to speed up builds that explains where I obtained this line in my Podfile `pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.14.0'`. Found [here](https://github.com/firebase/flutterfire/blob/3244f086ccd4dab98fb214543da0a716a5b61f94/docs/firestore/overview.mdx) in the history.

The biggest problem with the migration is the suddenness. I knew where to find these items in the previous documentation. A much friendlier way of migrating the documentation would have been to leave up the old Flutterfire documentation and then, for each page, remove the content and link to the new documentation. That would have acted as a checklist to ensure that each item has the documentation and would have given the rest of us the ability to follow the breadcrumbs to the new source of truth.

**Comment by maganap** [comment]
Original flutterfire documentation had a wonderful (and beautiful) flow for: installation -> getting started -> common use examples -> API reference. A summary list of all flutterfire packages with their latest version and a link to their respective pub.dev site and the API reference was so useful as well.

Now it's all mixed up pointing to no where useful but some generic Google documentation that gives no clues on how to do anything compared to the previous documentation. Most links are pointing to https://firebase.google.com/docs/flutter/setup?platform=ios instead of the respective package documentation.

Most documentation in Google docs include iOS, Android, Web... but no Flutter. The ones that do, have that typical Google documentation which is very annoying compared to the original flutterfire guide. I know it's very subjective but... I really felt flutterfire docs were an evolution (like Firebase docs, which are very nice as well). Now they all pointing to Google docs is just like going backwards.

I understand it's easier to maintain all together but... so... sniff... 😢  I just miss them. Aversion to change, I guess.

**Comment by kevinthecheung** [comment]
Okay everyone, you're right. This was too abrupt. I've restored the old docs, and added links to their new location.

https://firebase.flutter.dev/docs/overview

Thanks for all of your input.
