### ISSUE TITLE
🐛 Execution failed for task ':firebase_core:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by shah000** [firebase/flutterfire#8686]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_core:compileDebugJavaWithJavac'.
> Failed to calculate the value of task ':firebase_core:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'.
   > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, F:\Personal_Idea\ironshop-master\E_laundry\build\firebase_core\generated\ap_generated_sources\debug\out)) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@28824828) before task ':firebase_core:compileDebugJavaWithJavac' has completed is not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@shah000 
This doesn't seem to be related to Flutterfire. See same issue with solution and check if it helps. https://stackoverflow.com/questions/69250589/firebase-corecompiledebugjavawithjavac

Also, when you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Just posting the error isn't much helpful without looking at code and other details.
