### ISSUE TITLE
sign in Where is Google Desktop 

### ISSUE THREAD

**Issue by MROOT-user** [firebase/flutterfire#8885]
---

**Comment by maheshmnj** [comment]
@MROOT-user  Are you proposing to have auth plugin for Desktop? if so  you may try using this https://github.com/invertase/flutterfire_desktop


 When opening issues, please try to fill in some or all of the information requested in the issue template. This issue is currently not actionable on our side due to lack of information, If you have further info for us feel free to write in the comments and we will reopen it.
