### ISSUE TITLE
Unsecure function arc4random() using in flutter IOS

### ISSUE THREAD

**Issue by spdeol20** [firebase/flutterfire#8962]
## Bug report

**Unsecure function arc4random() using in flutter IOS**

arc4random() is using while using the flutter IOS part and Its raised through the testing process
can you please let me know, Is there any way to get rid of it or can we prevent Flutter IOS module 
so I can use it in android only

### Steps to reproduce

1. Go to 'search for arc4random().'
2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

  firebase_core: ^1.11.0
  firebase_core_web: ^1.5.3
  firebase_messaging: ^11.2.5
  firebase_messaging_web: ^2.2.6
<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>
<img width="746" alt="Screen Shot 2022-06-24 at 3 03 46 AM" src="https://user-images.githubusercontent.com/42397433/175530788-fe32b8ad-c680-4a03-bd0b-58d2ebd9ddb3.png">
<img width="692" alt="Screen Shot 2022-06-24 at 3 09 19 AM" src="https://user-images.githubusercontent.com/42397433/175530790-dbf5d581-31d6-414b-adf6-484836acb242.png">

---

**Comment by darshankawar** [comment]
@spdeol20 Thanks for the report. I am not sure if this is specific to Flutter or flutterfire plugins because they are just wrappers around native firebase sdks. 
When does it show the said function ? Is there any specific code sample ?
Also, from the table that you shared above, `arc4random` seemed to be used by `objective-c`, but Flutter now seems to be using Swift, so can you try creating new Flutter project that uses Swift by default and see if you still get to see the said function ?

**Comment by spdeol20** [comment]
Hi 
What other information do you want because it's clearly showing on the documentation that it's an insecure function as you can see in the picture? so pls check with your testing team

**Comment by darshankawar** [comment]
I think this should be reported in Apple developer forum instead at client side, because clients like Flutterfire leverages the native code. From the chart you shared, it seems to be coming from Objective C's implementation which Flutterfire is not using probably, as it is using Swift.
I suggest you open this issue in Apple developer forum. https://developer.apple.com/support/forums/
Closing from here. If you disagree, write in comments and I'll reopen it.
