### ISSUE TITLE
🐛 [Realtime Database] The data that is uploaded repeats itself

### ISSUE THREAD

**Issue by omer-rm** [firebase/flutterfire#8980]
before flutter 3 i was updating my data in firebase realtime database like this : 
```
    dailydata.set({
          "name": SharedPref.user_id,
          "router_bssid": thisWifiObject!.bssId,
          "date": dailyWorkTime,
          "startingTime": startingTime,
          "endingTime": endingTime,
          "totalWorkTime": SharedPref.hours == 0 ? 0 : SharedPref.hours,
          "percent": SharedPref.percent == 0 ? 0.0 : SharedPref.percent,
          "connectedfrom": thisWifiObject!.macAddress,
        });
```
and it was updating the values inside the dailydata database without duplicateing the the refrence (dailydata) >but after version 3 it become duplicate the refrence multiple times like this .. 
```
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata
dailydata 
```
as new refrence ...
![firebase error](https://user-images.githubusercontent.com/61887055/175940802-8f9ae7b7-ca70-4bf5-8dd1-33e8a79d8864.PNG)

**Comment by darshankawar** [comment]
@omer-rm 
When you open an issue, try to use new issue template and fill out requested details so that we'll have enough details to work with. Currently, the details you provided isn't enough to debug further. Can you provide `flutter doctor -v`, plugin version along with a minimal complete reproducible code sample that shows the current behavior ?

Also, try to use the plugin's official [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database/example) code and see if using it too, you get the same behavior or not.

**Comment by omer-rm** [comment]
i use update instade of set and now its working fine

**Comment by darshankawar** [comment]
Thanks for the update. Closing per above comment as resolved.
