### ISSUE TITLE
🐛 [firebase_app_check] SafetyNet discontinuation

### ISSUE THREAD

**Issue by dpedrinha** [firebase/flutterfire#9085]
I'm being warned that SafetyNet will be discontinued and that I should migrate to Play Integrity API before June 2023.

Will this plugin make the migration?

**Comment by darshankawar** [comment]
Thanks for the report @dpedrinha.
This issue should probably report at native firebase sdk repo, ie, here: https://github.com/firebase/firebase-android-sdk/issues, because the changes probably need to be done at native sdk level that flutterfire can leverage.
There's similar issue open for your reference: https://github.com/firebase/firebase-android-sdk/issues/3890

Closing from here.
