### ISSUE TITLE
🐛 [firebase_core_web 1.7.0] is not working for web on flutter master channel

### ISSUE THREAD

**Issue by Alecia1997** [firebase/flutterfire#9132]
Receiving the following when running on web (Master Channel) -> Error: Assertion failed
<img width="1191" alt="Screenshot 2022-07-18 at 09 21 30" src="https://user-images.githubusercontent.com/59566103/179462306-b54c0368-d712-4b48-85d2-29cdaa0a2b54.png">

**Comment by flutterninja9** [comment]
I fixed it by passing "options" in Firebase.initializeApp() method

**Comment by darshankawar** [comment]
@Alecia1997 
Do you get same error using previous version of it ? `firebase_core_web: 1.6.6` ?
If not, then it could be related to an ongoing issue with `flutter_core_web` that you can follow-up in for further updates.

https://github.com/firebase/flutterfire/issues/9106
https://github.com/firebase/flutterfire/issues/9124#issuecomment-1186477704

**Comment by deepak786** [comment]
I have the same issue on the web using flutter stable version 3.0.2.

In the project, firebase_core is defined as 
```
firebase_core: 1.19.1
```
Note there is no symbol (^) before the version number. It means I want to use this version strictly.

This version 1.19.1 uses 
```
firebase_core_platform_interface: ^4.4.3
firebase_core_web: ^1.6.6
```

Note: firebase_core_web version is ^1.6.6.
It means when getting the dependencies, it can be 1.6.6, 1.6.7, 1.6.8, 1.6.9, and so on.
But it should not be 1.7.0.

When I build the project, it is taking firebase_core_web: 1.7.0
Please check the attached screen from CI (CodeMagic).

![Screen Shot 2022-07-18 at 9 47 41 PM](https://user-images.githubusercontent.com/14223997/179556390-170aee5b-3486-486e-9493-bf497923182e.png)

Due to version 1.7.0, the web build is not working.

The question is why the dependency version is resolved to 1.7.0

is this correct behavior?

**Comment by DerickVanDerSandt** [comment]
@Alecia1997 also getting the same error. Downgrading all packages seems like the only way at the moment. @google-oss-bot Please advise on a different solution

**Comment by darshankawar** [comment]
This could be related to web JS SDK v9 which is the current version for which an issue is filed that you can track: 
https://github.com/firebase/firebase-js-sdk/issues/6445

I am able to replicate the same error as mentioned here: https://github.com/firebase/flutterfire/issues/9106#issuecomment-1187005792

**Comment by deepak786** [comment]
It seems that we have to pass the Firebase options when initializing the Firebase from the dart side using `Firebase.initializeApp()`.

**Comment by russellwheatley** [comment]
Yes, you have to pass `FirebaseOptions` for the web platform. `flutterfire configure` will write the file, and you just have to import the generated options file and pass into `options` for `Firebase.initializeApp()`.
