### ISSUE TITLE
cloud_firestore can't applied to my flutter app

### ISSUE THREAD

**Issue by MohamedMamdouh-432** [firebase/flutterfire#9133]
my project is completed but once i added cloud_firestore and import it's package , that is happen !!
![Screenshot (92)](https://user-images.githubusercontent.com/82661266/179474989-42d4019d-660d-49b1-a4f2-4cc37f6c85fb.png)

I hope this problem is being solved . thanks

**Comment by darshankawar** [comment]
@MohamedMamdouh-432 
When opening an issue, please try to use new issue template and fill out requested details so that we'll have enough details to work with. Just posting screenshot (which should be avoided) isn't enough to help us debug the issue.

Closing this issue for now, as no information is provided.

**Comment by MohamedMamdouh-432** [comment]
thanks very much . i already solve my problem and my app run successfully .
i will do what you want next time .
