### ISSUE TITLE
[firebase_dynamic_links] Clicking on a dynamic link inside the mail program causes strange behaivor

### ISSUE THREAD

**Issue by Epikur86** [firebase/flutterfire#9136]
## Bug report

I have generated a dynamic link, which I send through a firebase function to my email account. When opening the link on my android phone, I select the option to open the link through the installed flutter app. Then it opens the flutter app, when I minimize the flutter app and open the mail program, it still opens the flutter app. For users it's confusing, when they open their mail program, but instead it opens the flutter app. The user have to close the mail program to solve this issue, which is not obvious.

I use BlueMail on my phone.

**Comment by darshankawar** [comment]
@Epikur86 
Do you get expected behavior if you use any other email client other than `BlueMail` such as `gmail` ?
If so, then the behavior you are seeing may not be in control of flutterfire and it isn't something we can fix I'm afraid. It is very likely an issue with the way the BlueMail email client handles the dynamic link. It's probably worth raising this as an issue with Firebase Support and see what feedback do you get.

**Comment by Epikur86** [comment]
> @Epikur86 Do you get expected behavior if you use any other email client other than `BlueMail` such as `gmail` ? If so, then the behavior you are seeing may not be in control of flutterfire and it isn't something we can fix I'm afraid. It is very likely an issue with the way the BlueMail email client handles the dynamic link. It's probably worth raising this as an issue with Firebase Support and see what feedback do you get.

On Gmail it is working like expected. Thank you. Issue can be closed.

**Comment by darshankawar** [comment]
Thanks for confirming. Closing as not a plugin issue.
