### ISSUE TITLE
[📚] [firebase_app_check] Play Integrity Support

### ISSUE THREAD

**Issue by cnkygmr** [firebase/flutterfire#9178]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:
While examining it, I noticed that this plugin does not support Play Integrity. And I wonder when it will be added.

**Comment by ronnicknachok** [comment]
@cnkygmr I am not sure that is a true position that the plugin does not support Play Integrity - it does. I have built an app that uses the plugin and is correctly setup to use both **Play Integrity** and **SafetyNet**. Here is a screenshot from Firebase Console 
<img width="994" alt="Screen Shot 2022-07-22 at 10 46 49 PM" src="https://user-images.githubusercontent.com/28990386/180517559-d0d06bc9-92d3-4c63-84cc-62cacb9e50c3.png">

Here is the Flutter App Check documentation https://firebase.google.com/docs/app-check/flutter/default-providers have you had a chance to see this? 

Essentially to setup both **Play Integrity** and **SafetyNet** you just need the SHA-256 certificate fingerprint of both your development and production keystores Cc @darshankawar

**Comment by cnkygmr** [comment]
@ronnicknachok 

Hello,

I mean, when you browse the codes, there is nothing about playintegrity, there is only safetynet, this safety net is going up, google sent mail, I want you to change this code with safetynet.

You can check it out here:
[https://github.com/firebase/flutterfire/blob/7132d771ed5ada7a0433232b9f0d996ef0d61481/packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java#L73-L82](https://github.com/firebase/flutterfire/blob/7132d771ed5ada7a0433232b9f0d996ef0d61481/packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java#L73-L82)

When you activate the code, only safetynet works.


FirebaseApp.initializeApp(/*context=*/this)
val firebaseAppCheck = FirebaseAppCheck.getInstance()
firebaseAppCheck.installAppCheckProviderFactory(
    PlayIntegrityAppCheckProviderFactory.getInstance()
)

I activated playintegrity with this code, but this time firebase initializes 2 times..

**Comment by ronnicknachok** [comment]
@cnkygmr I think this is because you are mixing two implementations from your code above I can see Kotlin code sample from https://firebase.google.com/docs/app-check/android/play-integrity-provider#initialize which means you used the Android version of integration and not the Flutter version. The Flutter version does not require adding the Kotlin code. By any chance in your build.gradle on Android project..do you have this entry implementation **'com.google.firebase:firebase-appcheck-playintegrity'** ?

As per this documentation https://firebase.google.com/docs/app-check/flutter/default-providers once you `flutter pub add firebase_app_check` and `flutter pub get` then one line of code sets it all like in this sample 
`import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

// Import the firebase_app_check plugin
import 'package:firebase_app_check/firebase_app_check.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: 'recaptcha-v3-site-key',
  );
  runApp(App());
}`

**Comment by cnkygmr** [comment]
@ronnicknachok 

```
await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: 'recaptcha-v3-site-key',
  );
```

but I showed you the code, when you use this code, only safetynet is active
