### ISSUE TITLE
🐛 [firebase_messaging] Android "title" and "body" get priority over "titleLocKey" and "bodyLocKey"

### ISSUE THREAD

**Issue by GP4cK** [firebase/flutterfire#9207]
## Bug report

When the user receives a notification, I would like it to be translated using the keys in the strings.xml. If the user has not updated the app, it should then use the `title` and `body` parameters to display a default text (probably in English).

I don't know if this is the expected behaviour, it's not super clear in the [docs](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.androidnotification.md).

### Steps to reproduce

```json
    {
      "notification": {
        "title": "Default title", // If you remove these 2 lines, then the xLocKey will be used
        "body": "Default body"
      },
      "android": {
        "notification": {
           "titleLocKey": "hello_world",
           "bodyLocKey": "hello_world"
        }
      }
    }
```

### Expected behavior

I would expect the app / OS to first look if the translations are in the strings.xml file and if not, use the title and the body as a backup.

### Sample project

I can create a Sample project if necessary.

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: ^1.20.0
firebase_messaging: ^12.0.1
```

</details>

**Comment by darshankawar** [comment]
@GP4cK 
This is something probably need to be addressed at native side rather than at client, because flutterfire plugins are wrappers around native firebase sdks and send, receive data through Dart. So I suggest you to file this issue here https://github.com/firebase/firebase-android-sdk/issues for further resolution.

Closing from here. If you disagree, write in comments and I'll reopen it.
