### ISSUE TITLE
🐛 [cloud_firestore] Not getting live chat message data same time on multiple devices.

### ISSUE THREAD

**Issue by Javed-Sheta** [firebase/flutterfire#9234]
I am creating one chat application using Cloud Firestore. When I send messages from two devices at the same time then I am not able to receive messages on any one device. It is only working with a single device when the timeframe is the same for sending the messages.

Here is my code for receiving live messages :

FirebaseFirestore.instance
        .collection('conversations')
        .doc(convoID)
        .collection("messages")
        .orderBy("sent_date", descending: true)
        .limit(1)
        .snapshots()
        .forEach((element) {
    
AppUtil.printData( "== MESSAGE RECEIVED ==");
      
    });

**Comment by darshankawar** [comment]
@Javed-Sheta 
Your question is better suited for support channels like StackOverflow, so please ask the same there. 
Also check this video and see if it helps in your case: https://www.youtube.com/watch?v=DqJ_KjFzL9I

Closing from here, as this is more of a support question rather than bug or feature request.
