### ISSUE TITLE
flutterfire_ignore_scripts is null and crashes

### ISSUE THREAD

**Issue by sgehrman** [firebase/flutterfire#9255]
Yeah, still happens in every one of my projects using firebase_core.

I'm on web if that matters.  Reported this a while ago, never got back because I thought it was obvious.

![gnome-shell-screenshot-A5Z9P1](https://user-images.githubusercontent.com/287137/181652759-7e1e3ac6-91cd-497f-abaf-64703aa7a488.png)

Since there haven't been any recent updates here, I am going to close this issue.

@sgehrman if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.

_Originally posted by @google-oss-bot in https://github.com/firebase/flutterfire/issues/7701#issuecomment-1014070117_

**Comment by sgehrman** [comment]
turn on 'All Exceptions' and 'Uncaught Exceptions' in the vscode debugger.

**Comment by darshankawar** [comment]
Could it be related to the other error you reported ? https://github.com/firebase/flutterfire/issues/9256, because it seems the reported method is called inside `_initializeCore()`:

https://github.com/firebase/flutterfire/blob/c2771a425bd7260b11970e9e9e77ef40a39f9f16/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L107

But since you are not able to initialize it as mentioned in other issue, this exception could be triggering.

Please check [this](https://github.com/firebase/flutterfire/issues/9256#issuecomment-1198876909) and see if after successfully initializing the Firebase app, if you still get the same error or not.

**Comment by SKnoedler** [comment]
I am having the same problem 

> Could it be related to the other error you reported ? #9256, because it seems the reported method is called inside `_initializeCore()`:
> 
> https://github.com/firebase/flutterfire/blob/c2771a425bd7260b11970e9e9e77ef40a39f9f16/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L107
> 
> But since you are not able to initialize it as mentioned in other issue, this exception could be triggering.
> 
> Please check [this](https://github.com/firebase/flutterfire/issues/9256#issuecomment-1198876909) and see if after successfully initializing the Firebase app, if you still get the same error or not.

I am having the same problem and I added the proper config as shown by Lyokone. The issue does not  appear if I run "flutter run --verbose" or if build the entire web application first. If I run "flutter run" oder "Run Without Debugging" or "Start Debugging" it fails initializing firebase. I am very confused. What does the verbose mode change?

**Comment by Lyokone** [comment]
Hello @SKnoedler
Could you create a full reproduction so I can take a look?
