### ISSUE TITLE
I can't filter data with collectionGroup

### ISSUE THREAD

**Issue by edsonISA** [firebase/flutterfire#9275]
https://user-images.githubusercontent.com/85927029/182054716-d08cd6d2-b461-4eb1-bb45-f1c0992b900f.mp4

![IMG_20220731_113636](https://user-images.githubusercontent.com/85927029/182055228-0b4e6df2-b798-4673-a520-e689baf8faba.png)

When i filter data with collectionGroup, it shows only for a moment, then it shows me as if it is loading the data but never finish.
When I use collection and filter the data I don't have any problem, I want it to work in the same way with collectionGroup since it is the simplest way to access several sub collections

**Comment by darshankawar** [comment]
@edsonISA 
When you open an issue, please use [new issue template](https://github.com/firebase/flutterfire/issues/new/choose) and fill out requested details so that we'll have enough info to work with.
Also, the video you shared isn't playing, and please avoid posting screenshots.
Closing for now, as this issue isn't actionable due to lack of details.
