### ISSUE TITLE
🐛 [google_sign_in] The supplied auth credential is malformed or has expired. [ Invalid Idp Response: access_token audience is not for this project ]

### ISSUE THREAD

**Issue by iamsannyrai** [firebase/flutterfire#9349]
I have used two firebase project for single application to maintain two different environment and trying to authenticate using google sign in using dart-only initialization.
The problem is whenever I try to signin in one of the project, I get above error. All the information of firebase options matches with details in google-services.json for the project.

**Comment by darshankawar** [comment]
@iamsannyrai Looking at the error, it doesn't seem to be specific to FlutterFire, but could be due to the configuration based on two different environments, as the error indicates `the access_token audience is not for this project`, ie, the client is properly identifying the error.

Take a look at [this](https://github.com/react-native-google-signin/google-signin/issues/300#issuecomment-381358723) solution and see if it helps in your case.

Closing from here, as this isn't specific to Flutterfire. If you disagree, write in comments and I'll reopen it.

**Comment by iamsannyrai** [comment]
@darshankawar I have reviewed all the key values present in firebase_options.dart with google-services.json file. They match. [This](https://github.com/react-native-google-signin/google-signin/issues/300#issuecomment-381358723) doesn't seem to solve my problem.

**Comment by darshankawar** [comment]
@iamsannyrai 
I suggest you to reach out to [firebase support](https://firebase.google.com/support) for further resolution.
