### ISSUE TITLE
Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found

### ISSUE THREAD

**Issue by t00fi** [firebase/flutterfire#9389]
when ever using cloud_firestore to upload data or get data from firebase it gives this error

**Comment by darshankawar** [comment]
@t00fi 
When opening an issue, please use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.
Currently, no details are provided so we can't proceed to make it actionable. 
Closing for now due to lack of details.
