### ISSUE TITLE
[📚] Crashlytics documentation logs non-fatal errors as fatal

### ISSUE THREAD

**Issue by oodavid** [firebase/flutterfire#9417]
We updated our crashlytics implementation to match the newer documentation.

The documentation _appears_ to log everything as a fatal crash. Even non-fatal errors.

https://firebase.google.com/docs/crashlytics/get-started?platform=flutter

What we're seeing is that iOS logs everything as fatal, but Android appears to work as expected.

iOS shows everything as a fatal error, I've manually triggered non-fatal errors to test this:
<img width="342" alt="Screenshot 2022-08-24 at 13 45 29" src="https://user-images.githubusercontent.com/46879/186421850-71b1155a-c770-404f-8156-4941c3ec8d3b.png">

Android seems to be OK
<img width="523" alt="Screenshot 2022-08-24 at 13 45 14" src="https://user-images.githubusercontent.com/46879/186421853-d7e004a0-28ae-4b14-b3a5-4a599c8267cf.png">

**Comment by darshankawar** [comment]
Thanks for the report. This seems to be happening probably because of 
`FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;` indicating all errors are recorded as Fatal.

https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#configure-crash-handlers

Which seems to be similar to what is described here: https://github.com/firebase/flutterfire/issues/8815, so I am going ahead and closing this in favor of https://github.com/firebase/flutterfire/issues/8815 and will forward to the team on their insights.

If you disagree, write in comments and I'll reopen it.
