### ISSUE TITLE
🐛 [cloud_firestore_odm] json_serializable's field property ignore doesn't work for getters

### ISSUE THREAD

**Issue by bsr203** [firebase/flutterfire#9419]
Hello,

[This](https://github.com/firebase/flutterfire/pull/9030/files) pr add support to ignore properties.

below getter 
```
  @JsonKey(ignore: true)
  String get documentId {
    assert(id != null);
    return id!;
  }
```
still adds these entries (twice)
```
  XYZQuery whereDocumentId({
 ...
   XYZQuery orderByDocumentId({
...

```

using as below works.
```
  @JsonKey(ignore: true)
  String? documentId;
```

**Comment by rrousselGit** [comment]
Looking at this issue, do we even want to support getters?

Since getters are not available in the Firestore DB, I don't see how doing something like `whereMyGetter(..)` would ever be useful.


So rather than applying `JsonKey(ignore: true)` to getters, wouldn't it make more sense to ignore all getters entirely?
They aren't present in the JSON after-all.
