### ISSUE TITLE
🐛 firebase_auth found internal error

### ISSUE THREAD

**Issue by RjMakwana2660** [firebase/flutterfire#9449]
While adding package i found this kind of errors which are from internal package code as attached here with 

```
Because firebase_auth >=3.6.1 <3.6.2 depends on firebase_auth_platform_interface ^6.5.1 and firebase_auth >=3.6.2 <3.6.3 depends on firebase_auth_platform_interface ^6.5.2, firebase_auth >=3.6.1 <3.6.3 requires firebase_auth_platform_interface ^6.5.1.
And because firebase_auth >=3.6.3 <3.6.4 depends on firebase_auth_platform_interface ^6.5.3, firebase_auth >=3.6.1 <3.6.4 requires firebase_auth_platform_interface ^6.5.1.
And because firebase_auth >=3.6.4 <3.7.0 depends on firebase_auth_platform_interface ^6.5.4 and firebase_auth >=3.7.0 depends on firebase_auth_platform_interface ^6.6.0, firebase_auth >=3.6.1 requires firebase_auth_platform_interface ^6.5.1.
Because every version of flutter from sdk depends on collection 1.15.0 and firebase_auth_platform_interface >=6.4.0 depends on collection ^1.16.0, flutter from sdk is incompatible with firebase_auth_platform_interface >=6.4.0.
Thus, flutter from sdk is incompatible with firebase_auth >=3.6.1.
So, because freetimeproject_codes depends on both flutter from sdk and firebase_auth ^3.6.1, version solving failed.
pub get failed (1; So, because freetimeproject_codes depends on both flutter from sdk and firebase_auth ^3.6.1, version solving failed.)
```

**Comment by darshankawar** [comment]
@RjMakwana2660 
Can you provide `flutter doctor -v`, `pubspec.yaml` and adding which package throws this error ?

**Comment by RjMakwana2660** [comment]
[pubspec.txt](https://github.com/firebase/flutterfire/files/9461549/pubspec.txt)
@darshankawar here is attached pubspec.yaml

currently i have managed it with downgrading the firebase_auth version to **firebase_auth: ^3.3.19**

**Comment by darshankawar** [comment]
Thanks for the update. From `pubspec.yaml` file you shared, I see that it has `flutter_test` dependency which uses or depends on ` collection: ^1.15.0`, but `firebase_auth` version you were trying to add requires `collection` package to be `^1.16.0` and hence due to this conflict, you are getting the error. (`Because every version of flutter from sdk depends on collection 1.15.0`)

You will need to use latest `flutter_test` dependency which is dependent on your sdk version. Currently you are using `sdk: ">=2.16.2 <3.0.0"` which you need to upgrade to latest available which will also update your `flutter_test`. This should resolve your issue.



> currently i have managed it with downgrading the firebase_auth version to **firebase_auth: ^3.3.19**

You don't need to do this. Upgrading your sdk constraint should resolve the issue.

Closing as above should work.
