### ISSUE TITLE
Ios recieve notification in foreground

### ISSUE THREAD

**Issue by rulefahd** [firebase/flutterfire#9614]
My issue here is fcm shows notification when app is in foreground on IOS, which I don't want, I tried to set notification foreground options to
Alert : false, Badge : false,  sound : false
But still
How I can i stop fcm to show notifications if app is on foreground on IOS?

**Comment by darshankawar** [comment]
@rulefahd 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a `how to` question instead of a bug or feature request.

If you think the behavior you are seeing is indeed a bug in the latest version of plugin, please use new issue template and provide requested details so that we can address it properly.
