### ISSUE TITLE
🐛 [firebase_messaging] Subscribers not Receiving Notifications

### ISSUE THREAD

**Issue by mado-bohsali** [firebase/flutterfire#9675]
My subscribers aren't receiving notifications although I didn't change my code since Spring 2021. The flutter dependencies I rely on are:
firebase_messaging: ^10.0.4
firebase_core: ^1.4.0

**Comment by mado-bohsali** [comment]
No implementation found for method Messaging#requestPermission on channel plugins.flutter.io/firebase_messaging

**Comment by darshankawar** [comment]
@mado-bohsali 
Thanks for the report, but the plugin versions you are using are very old. I suggest you to upgrade them to latest available versions along with framework version and try again to see if you still get same behavior or not.

Also, we would prefer you to use new issue template and fill out requested details so that we will have enough info to work / analyze the issue.

Closing for now.

**Comment by mado-bohsali** [comment]
@darshankawar thanks dear! I will work on that. The weird thing I noticed is that the promise gets resolved (upon launching the fire function) and still users do not receive.
