### ISSUE TITLE
🐛 [firebase_storage] File upload is not working on Flutter Web

### ISSUE THREAD

**Issue by dhruvilxcode** [firebase/flutterfire#9677]
## Bug report

**Describe the bug**
File upload using putFile/putBlob/putData methods not working on Flutter Web.
Works fine on Android & iOS.

### Steps to reproduce

1. Pick a file object using image_picker
2. upload it to firebase storage using any of the following methods. putFile(), putBlob(), putData()

### Expected behavior

The file should be uploaded to Firebase Storage.

**Comment by darshankawar** [comment]
@dhruvilxcode 
When you say, `not working`, do you see any error in the console or in browser ?
Also, when you open an issue, please use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.

**Comment by anmolguptach** [comment]
Instead of file use uint8list

**Comment by dhruvilxcode** [comment]
I tried but doesn't work, i even tried BLOB, which is specifically for the WEB only.

**Comment by dhruvilxcode** [comment]
@darshankawar Thanks for the comment.
I am seeing one error, but it's not giving much context about the error.
