### ISSUE TITLE
🐛 [Firebase Auth] visibility of "identities" in id token

### ISSUE THREAD

**Issue by sharabiddin** [firebase/flutterfire#9692]
## Bug report

**Optional Visibility**

Visibility of "firebase-> identities" in id token must be regulated by property. By "Man in the middle attack" will be easy to acquire users' identity info

### Steps to reproduce

1. Add optional bool check `getIdToken(secure: true)` method

###Example

`{`
 ` "iss": "https://securetoken.google.com/test-api",`
 ` "aud": "test-api",`
`  "auth_time": 1665253603,`
  `"user_id": "*********",`
 ` "sub": "************",`
 ` "iat": 1665253603,`
 ` "exp": 1665257203,`
`  "email": "test@gmail.com",`
 ` "email_verified": false,`
`  "firebase": {`
 `   "identities": {`
 `     "email": [`
 `       "test@gmail.com"`
 `     ]`
  `  },`
   ` "sign_in_provider": "password"`
  `}`
`}`
`

**Comment by darshankawar** [comment]
@sharabiddin 
Thanks for the report. Can you provide the requested details in the [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) so that we'll get better idea of the issue ?


> 1. Add optional bool check `getIdToken(secure: true)` method

Where are you referencing this to be added ?
