### ISSUE TITLE
[firebase_messaging]: <FirebaseMessaging.onBackgroundMessage dont work when app is closed>

### ISSUE THREAD

**Issue by VictorJGarciaMartin** [firebase/flutterfire#9718]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![Captura de Pantalla 2022-10-12 a las 20 51 32](https://user-images.githubusercontent.com/32029675/195425047-5edaab51-9f52-4f87-aa54-b783b80c3c86.png)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![Captura de Pantalla 2022-10-12 a las 20 57 03](https://user-images.githubusercontent.com/32029675/195425705-b7c16d7e-1d1d-4b81-9842-1c6a181729e5.png)

### Have you disabled method swizzling for Firebase in your app?

![Captura de Pantalla 2022-10-12 a las 21 00 40](https://user-images.githubusercontent.com/32029675/195426208-458cdef6-083f-4f8a-b95f-0a106b39a804.png)

### Are you sending messages to your app from the Firebase Admin SDK?

![Captura de Pantalla 2022-10-12 a las 21 01 48](https://user-images.githubusercontent.com/32029675/195426382-8fd92a42-6c00-46b3-8382-feaa88c4cee9.png)

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

![Uploading Captura de Pantalla 2022-10-12 a las 21.27.19.png…]()

### Additional context and comments

![Captura de Pantalla 2022-10-12 a las 21 28 35](https://user-images.githubusercontent.com/32029675/195431064-2cccf0d8-fc62-4f4c-883e-afb322b618da.png)

The FirebaseMessaging.onBackgroundMessage dont work when de app is closed

**Comment by VictorJGarciaMartin** [comment]
por omisión	21:26:53.549897+0200	dasd	Submitted Activity: com.apple.pushLaunch.com.example.notificacionesCarol:E6DEED at priority 10 <private>
por omisión	21:26:53.552995+0200	dasd	Push not allowed for <private>
por omisión	21:26:53.553275+0200	dasd	Daemon Canceling Activities: {(
    com.apple.pushLaunch.com.example.notificacionesCarol:E6DEED
)}
por omisión	21:26:53.553422+0200	dasd	CANCELED: com.apple.pushLaunch.com.example.notificacionesCarol:E6DEED at priority 10 <private>!
por omisión	21:26:53.553597+0200	dasd	Removing a launch request for application <private> by activity <private>
por omisión	21:26:53.553731+0200	dasd	Don't have <private> for type 0
por omisión	21:26:53.554068+0200	dasd	Don't have <private> for type 1
error	21:26:53.557734+0200	dasd	Activity <private> not tracked as being started, ignoring it

**Comment by darshankawar** [comment]
Thanks for the report @VictorJGarciaMartin 
Can you elaborate on your use case when you say `app is closed` ? Does that mean, 

1. You terminated the app by swiping away from app switcher ? 
2. Or when app is terminated, you opened another app and then sent notification with which `onBackground` handler isn't getting called ?
3. Is the behavior occurring consistently every time when you send notification ?
4. How are you verifying if background message handle works or not when the app is terminated?

**Comment by VictorJGarciaMartin** [comment]
1. You terminated the app by swiping away from app switcher ? --> Yes
2. Or when app is terminated, you opened another app and then sent notification with which onBackground handler isn't getting called ? --> I do not open another application
3. Is the behavior occurring consistently every time when you send notification ? --> Yes
4. How are you verifying if background message handle works or not when the app is terminated? --> 
I issue an http request to a REST service that updates a record in a database. This functionality works correctly when the application is open and in the background

**Comment by darshankawar** [comment]
> 1. You terminated the app by swiping away from app switcher ? --> Yes

According to [this](https://firebase.flutter.dev/docs/messaging/usage/#receiving-messages) document, it says:

`On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.
`
And this seems to be a general implementation of iOS, not specific to Firebase.

**Comment by ViniciusSossela** [comment]
@darshankawar the same happens on Android platform.
It was working on the previous version, but suddenly it stoped to work.

On Android either Background (Minimized) or Terminated (Closed) notifications are not working;
Foreground messages on Android is OK.

- in DEBUG mode all works, when we deploy, Background and Terminated doesn't work...
Already tried top-level anonymous Functions and also named functions... Nothing works!

**Comment by mDNA1198** [comment]
Hello. I also faced this issue. Please do the following.

**Comment by VictorJGarciaMartin** [comment]
If the application is closed, the solution of adding @pragma('vm:entry-point')has not worked for me

**Comment by developer-ashish31** [comment]
I also faced same issue on android release build when my app is in background and killed state not able to get push notification via **FirebaseMessaging.onBackgroundMessage**  just because i was called class method inside top level method so it cause error in background and killed state of application so make sure don't write any logic which depends on class method in top level method, **this block should only contain top level set of instruction.**

**Comment by ViniciusSossela** [comment]
Thanks @mDNA1198 and @darshankawar  .
You were right https://github.com/firebase/flutterfire/issues/9446#issuecomment-1240554285 solved the problem.

This [issue](https://github.com/firebase/flutterfire/pull/9494) should be released. Still didn't found the proposed solution in the docs:
https://firebase.google.com/docs/cloud-messaging/flutter/receive
https://firebase.flutter.dev/docs/messaging/usage

Thanks

**Comment by MohamedRisaldarTA** [comment]
I am facing similar problem on Android (On Samsung One UI 4 so far and seems no issues on Pixel devices).
FirebaseMessaging.onBackgroundMessage is not getting called for some alert notifications.(rarely but misses important notifications).
Implemented data messages with high priority and all notifications are having exact same configurations and I am missing 2-3 notifications daily.


I missed a notification on 10-17 18:05:43

Checked logs too:

Seems lmkd reclaims the memory and app got killed.
But activity manager launching it again and I lost my alert notification in between this. 

**10-17 18:05:26.953   568   568 I lmkd    : Reclaim '[com.something.app](http://com.something.app/)' (9011), uid 10471, oom_score_adj 955, state 19 to free 167164kB rss, 23664kb swap**
**10-17 18:05:27.021  1555  4840 I ActivityManager: Process [com.something.app](http://com.something.app/) (pid 9011) has died: cch+55 CEM (281,1698)**
10-17 18:05:42.058  1555  2167 D ActivityTaskManager: request preloading for newly launching app : com.something.app.MainActivity
10-17 18:05:42.059 18797 18797 D StartingSurfaceDrawer: preloadSplashScreenAppIcon [com.something.app](http://com.something.app/)
10-17 18:05:42.072  1555  1864 I ActivityManager: Start proc 10889:[com.something.app/u0a471](http://com.something.app/u0a471) for activelaunch {[com.something.app/com.something.app.MainActivity](http://com.something.app/com.something.app.MainActivity)}
10-17 18:05:42.102 10889 10889 E something.home.ap: Not starting debugger since process cannot load the jdwp agent.
10-17 18:05:42.104 10889 10889 E USNET   : USNET: appName: [com.something.app](http://com.something.app/)
10-17 18:05:42.109  1555  3412 I ActivityManager: DSS OFF for [com.something.app](http://com.something.app/)
10-17 18:05:42.117  1555  3412 D ActivityManager: attachApplicationLocked() app=ProcessRecord{e0188d0 10889:[com.something.app/u0a471](http://com.something.app/u0a471)} app.isolatedEntryPoint=null instr2=null
10-17 18:05:42.121 10889 10889 D ActivityThread: handleBindApplication()++ app=[com.something.app](http://com.something.app/)
10-17 18:05:42.167 10889 10889 V GraphicsEnvironment: ANGLE Developer option for '[com.something.app](http://com.something.app/)' set to: 'default'
10-17 18:05:42.168 10889 10889 D LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=[com.something.app](http://com.something.app/)appContext.mBasePackageName=[com.something.app](http://com.something.app/)
10-17 18:05:42.180 10889 10889 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.2.13 for [com.something.app](http://com.something.app/)
10-17 18:05:42.297 10889 10925 I FA      :   adb shell setprop [debug.firebase.analytics.app](http://debug.firebase.analytics.app/) [com.something.app](http://com.something.app/)
10-17 18:05:42.825  1555  3357 D MARs:ActiveTrafficFilter: filter : [com.something.app](http://com.something.app/)(0)
10-17 18:05:42.825  1555  3357 D FreecessController: [com.something.app](http://com.something.app/)(10471) is important[8]
10-17 18:05:44.851   839   839 E audit   : type=1400 audit(1666055144.845:243653): avc:  denied  { read } for  pid=10889 comm="[something.app](http://something.app/)" name="max_map_count" dev="proc" ino=44032291 scontext=u:r:untrusted_app:s0:c215,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 SEPF_SM-A715F_12_0001 audit_filtered
10-17 18:05:44.851   839   839 E audit   : type=1300 audit(1666055144.845:243653): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7ad6904e10 a2=0 a3=0 items=0 ppid=857 pid=10889 auid=4294967295 uid=10471 gid=10471 euid=10471 suid=10471 fsuid=10471 egid=10471 sgid=10471 fsgid=10471 tty=(none) ses=4294967295 comm="[something.app](http://something.app/)" exe="/system/bin/app_process64" subj=u:r:untrusted_app:s0:c215,c257,c512,c768 key=(null)
10-17 18:05:44.851   839   839 E audit   : type=1327 audit(1666055144.845:243653): proctitle="[com.something.app](http://com.something.app/)"
**10-17 18:05:45.091  1555  4805 I ActivityManager: Killing 10889:[com.something.app/u0a471](http://com.something.app/u0a471) (adj 905): AL_Kill : over 3 sec - I suspect that it got killed while starting to process the message.**
10-17 18:05:47.215  1555  1555 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|[com.something.app](http://com.something.app/)|g:something_alerts ,value= summary :  NotificationData { tag= null }  , child : 0 } 
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|0|null|10471
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|90878|null|10471
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|22457|null|10471
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|60294|null|10471
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|92974|null|10471
10-17 18:05:48.276 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|45835|null|10471
10-17 18:05:48.576  1555  1555 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|[com.something.app](http://com.something.app/)|g:something_alerts ,value= summary :  NotificationData { tag= null }  , child : 0 } 
10-17 18:05:52.828  1555  3357 D MARs:ActiveTrafficFilter: filter : [com.something.app](http://com.something.app/)(0)
10-17 18:05:52.828  1555  3357 D FreecessController: [com.something.app](http://com.something.app/)(10471) is important[8]
10-17 18:05:57.826 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|0|null|10471
10-17 18:05:57.826 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|90878|null|10471
10-17 18:05:57.827 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|22457|null|10471
10-17 18:05:57.827 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|60294|null|10471
10-17 18:05:57.827 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|92974|null|10471
10-17 18:05:57.827 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|45835|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|0|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|90878|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|22457|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|60294|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|92974|null|10471
10-17 18:05:57.854 18797 18797 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|[com.something.app](http://com.something.app/)|45835|null|10471
**10-17 18:06:02.841  1555  3357 D FreecessController: [com.something.app](http://com.something.app/)(state: Initial -> Freezeable, Reason: uidIdle)**

**Comment by hamishjohnson** [comment]
Setting 

```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```

in info.plist is what worked for me. (Disabling method swizzling)

@VictorJGarciaMartin i couldn't see that in your info.plist so give it a try

**Comment by eldarkk** [comment]
For those guys, who are getting issues with iOS silent pushes, maybe it will help.

What steps i made to have it working:
1) All setting set by documentation, method swizzling not disabled.
2) For Sending payload im using Insomnia:


payload below:
```json
{
	"to": "cgXQs9Ku7kGVgq4ypg5McT.......................",
	"priority": "high",
	"content_available": true,
	"data": {
		"id": "7",
		"type": "test"
	}
}
```

3) Registering handler:

- registering handler in void main() func
```dart
Future<void> _configureFirebaseMessaging() async {
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  try {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: false,
      badge: false,
      sound: false,
    );
  } catch (error) {
    FirebaseCrashlytics.instance.recordError(
        'setForegroundNotificationPresentationOptions: ' + error.toString(),
        StackTrace.empty);
    return Future.value();
  } finally {
    return Future.value();
  }
}
```
 
 
4) Top level function as you can see even without @pragma mark
- REQUIRED (!!!): **awaiting each step** and returning **Future.value(null)**

```dart
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await saveToPipedream(map: message.data);
  return Future.value(null);
}
```

 
 
5) Sending each delivered silent notification to pipedream (test backend you can say), very helpful to see delivered silent pushes.
- REQUIRED (!!!):  **awaiting each step** and returning **Future.value(null)**

```dart
Future<void> saveToPipedream({Map<String, dynamic>? map}) async {
  await Dio()
      .post('https://eozf*****.m.pipedream.net', data: map.toString());
  return Future.value(null);
}
```

For me, main issue was in: **awaiting of execution of each step** and **return Future.value(null)** after code gets executed.

And as you can see, its working super super stable. All Silent pushes got delivered.
<img width="378" alt="Снимок экрана 2022-10-22 в 16 46 47" src="https://user-images.githubusercontent.com/6400167/197335036-ef409e55-891f-48e5-81ae-d397ca435abe.png">

Peace for you, guys.

**Comment by wolru** [comment]
same here. I updated library from 13.0.4 to 14.0.4
In previos version, the background notification worked in terminated state.
But after update, that's not working

**Comment by Ankur2019** [comment]
For officail [example](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart),
I've found similar issue for **android**. I'm running on android emulator (Resizable Experimental API 33 (mobile)).

[Here](https://drive.google.com/file/d/1YVGlFfJZSfBLxdYX6o_ouIOi0qYcWaDQ/view?usp=sharing) is the recorded video. U can see that it works in **foreground**, **background** state. But not in **app closed** state. I've sent three different push notifcation for testing.

Here is the **console for run**
`Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:44275/wLwYH9XHnuo=/ws
Syncing files to device sdk gphone64 x86 64...
D/CompatibilityChangeReporter( 7159): Compat change id reported: 183155436; UID 10158; state: ENABLED
I/FirebaseApp( 7159): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
W/FlutterJNI( 7159): FlutterJNI.loadLibrary called more than once
I/ResourceExtractor( 7159): Found extracted resources res_timestamp-1-1667801762867
W/FlutterJNI( 7159): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI( 7159): FlutterJNI.init called more than once
I/FLTFireBGExecutor( 7159): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
D/EGL_emulation( 7159): eglCreateContext: 0x7f19fa533490: maj 3 min 1 rcv 4
D/EGL_emulation( 7159): eglCreateContext: 0x7f19fa5324d0: maj 3 min 1 rcv 4
D/HostConnection( 7159): createUnique: call
D/HostConnection( 7159): HostConnection::get() New Host Connection established 0x7f19fa533010, tid 7216
D/HostConnection( 7159): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
D/EGL_emulation( 7159): eglMakeCurrent: 0x7f19fa5324d0: ver 3 1 (tinfo 0x7f1c2589b280) (first time)
I/FLTFireMsgService( 7159): FlutterFirebaseMessagingBackgroundService started!
I/flutter ( 7159): FCM Token: cj3NXQuJQkmwBieAQmcdoZ:APA91bFMKOxKDcmoQO7JqwuNqqb0byz_7tLA3aaxMHSYS7jrXuBmpCSWRNvrlUmXRPGICWsvn8MwPD_y0jMnH08Yp3XVw9_HRAbyBMEYi_ZZNBrq-ikY_P16HWFLth0-WgJkdznT9zcW
E/SurfaceSyncer( 7159): Failed to find sync for id=0
W/Parcel  ( 7159): Expecting binder but got null!
D/FLTFireMsgReceiver( 7159): broadcast received for message
W/ssaging.example( 7159): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/ssaging.example( 7159): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/ssaging.example( 7159): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/ssaging.example( 7159): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
W/FirebaseMessaging( 7159): Unable to log event: analytics library is missing
W/FirebaseMessaging( 7159): Unable to log event: analytics library is missing
D/CompatibilityChangeReporter( 7159): Compat change id reported: 160794467; UID 10158; state: ENABLED
D/EGL_emulation( 7159): app_time_stats: avg=12995.88ms min=12.34ms max=38955.95ms count=3
D/FLTFireMsgReceiver( 7159): broadcast received for message
W/FirebaseMessaging( 7159): Unable to log event: analytics library is missing
I/flutter ( 7159): Handling a background message 0:1667802865649243%50d7604150d76041
Lost connection to device.
`

Here is **flutter doctor** result:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on Ubuntu 22.04.1 LTS 5.15.0-52-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
`

**Comment by elenacrst** [comment]
On my iOS device (iPhone 11 Pro, version 15.7.1), it seems to handle properly the FCM when app was terminated, if I'm using the version 13.0.4 as @wolru mentioned, with an implementation similar to @eldarkk .
This worked for me only on firebase_messaging 13.0.4, does not work on 14.0.4 and I'm using topics only.
I'm ale to show my own notification with flutter_local_notifications package and report an API call to pipedream.
I noticed the OS won't allow my app to handle the FCM if it has the same content and it's send twice, but if I change for example a field within my 'data', it is handled.
Does the issue with sending FCMs occur on specific iOS versions?

**Comment by darshankawar** [comment]
For everyone facing this issue in this thread, please check below comments / solutions and see if they work in individual's case:

https://github.com/firebase/flutterfire/issues/9718#issuecomment-1287607576
https://github.com/firebase/flutterfire/issues/9718#issuecomment-1287760697

**Comment by test0terter0n** [comment]
Hey @darshankawar , I facing the same issue. For me background messages stopped working after upgrading from iOS 16.0 to iOS 16.1. The proposed solutions fro @eldarkk  and @hamishjohnson did not make any difference.

**Comment by hamishjohnson** [comment]
> For everyone facing this issue in this thread, please check below comments / solutions and see if they work in individual's case:
> 
> [#9718 (comment)](https://github.com/firebase/flutterfire/issues/9718#issuecomment-1287607576) [#9718 (comment)](https://github.com/firebase/flutterfire/issues/9718#issuecomment-1287760697)

My original solution no longer works for some reason

**Comment by marcinFDT** [comment]
also the same problem, it works on android but not on the iOS 
iOS 16.1.1 iPhone 14 Pro
firebase_messaging: ^14.1.1

**Comment by test0terter0n** [comment]
@darshankawar  and others: do you no if its required to setup apps ssl certificates in firebase?

**Comment by CWTgithub** [comment]
also the same problem, it works on android but not on the iOS
iOS 16.1.1 iPhone 14 Pro
firebase_messaging: ^14.1.3
flutter SDK: 3.3.9

**Comment by tigrenok00** [comment]
Same for IOS (android works)
firebase_messaging: ^14.2.1
flutter SDK: 3.7.0
iOS tested: 15.6.1 and 16.3

**Comment by russellwheatley** [comment]
Hey @VictorJGarciaMartin, the background message handler will not be executed when the app is in a terminated state on iOS. See [documentation here](https://firebase.google.com/docs/cloud-messaging/flutter/receive).

>On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.

Notifications will still be intercepted by the iOS SDK FirebaseMessaging pod and will still be displayed.
