### ISSUE TITLE
🐛 [firebase_auth] play-services-safetynet

### ISSUE THREAD

**Issue by NOU-VANNET** [firebase/flutterfire#9732]
The developer of play-services-safetynet (com.google.android.gms:play-services-safetynet) has reported critical issues with version 17.0.0. Consider upgrading before publishing a new release.

Here's what the SDK developer told us:
The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging.

**Comment by darshankawar** [comment]
@NOU-VANNET 
This issue need to be handled and fixed by native firebase sdk itself, so flutterfire plugins can't do much about it.
There's similar issue open in android firebase sdk github in which you can follow-up for further updates: https://github.com/firebase/firebase-android-sdk/issues/3890

Closing from here.
