### ISSUE TITLE
🐛 [firebase_analytics] [Regression] in_app_purchase event not reported

### ISSUE THREAD

**Issue by PawlikMichal25** [firebase/flutterfire#9738]
## Bug report

**Describe the bug**
Recently I upgraded the plugin from `9.3.6` to `9.3.8` and we noticed that `in_app_purchase` event stopped being reported in Firebase Console. To prove that this is a problem related firebase_analytics we reverted back to  `9.3.6` and released our app to production and the event started appearing again, so this is clearly a regression of the library.

With both `9.3.6` and `9.3.8` the event is correctly reported on Android, but it's not with `9.3.8` on iOS.

### Steps to reproduce

1. Release app to AppStore
2. Purchase non-consumable item (I don't know if subscriptions are correctly reported)
3. You will see events in AppStore (and money), but no events reported in Firebase Console

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by russellwheatley** [comment]
Look at the difference between the two releases:
https://github.com/firebase/flutterfire/compare/firebase_analytics-v9.3.6...firebase_analytics-v9.3.8

Search "analytics" and see that zero code changes were made to the API that would have an effect (There's a change to the error handling implementation. It was moved to a separate package. Nothing that would facilitate this issue.)
Search "firebase_sdk_version" and see that the iOS SDK version changed. It's more likely that. There is nothing we can do about that. I'd suggest creating a reproduction on a pure iOS app and creating an issue report to demonstrate the problem. Here is a [recent iOS app](https://github.com/invertase/ios-sdk-10-issues) that I used to reproduce an issue which I'd suggest you follow. I would've thought this issue is reproducible in debug mode. It will increase your chances of your issue being resolved if they don't have to release to the app store to reproduce. Hope that helps.
